// Generated by apps/api/scripts/generate_contracts.py. Do not edit.
import type { Versions, BriefContent, RawArtifact, SufficiencyAssessment } from "../src/generated";

export const versions: Versions = {
  "brief": 1,
  "plan": 1,
  "evidence_bundle": null,
  "category_catalog": null,
  "source_registry": null,
  "connectors": {
    "source-0017": "connector-v1"
  },
  "prompts": {
    "brief": "prompt-v1"
  },
  "model": null,
  "normalizer": null,
  "extractor": null,
  "decision_policy": null,
  "validator": null
};

export const brief: BriefContent = {
  "original_idea": "Öğrenciler için not araması",
  "normalized_idea": null,
  "product_type": {
    "value": null,
    "state": "missing",
    "origin": null,
    "assumption_id": null,
    "conflicting_values": [],
    "prior_origins": [],
    "confirmed": false
  },
  "target_user": {
    "value": null,
    "state": "missing",
    "origin": null,
    "assumption_id": null,
    "conflicting_values": [],
    "prior_origins": [],
    "confirmed": false
  },
  "problem_or_job": {
    "value": null,
    "state": "missing",
    "origin": null,
    "assumption_id": null,
    "conflicting_values": [],
    "prior_origins": [],
    "confirmed": false
  },
  "context_or_niche": {
    "value": null,
    "state": "missing",
    "origin": null,
    "assumption_id": null,
    "conflicting_values": [],
    "prior_origins": [],
    "confirmed": false
  },
  "market_scope": {
    "value": null,
    "state": "missing",
    "origin": null,
    "assumption_id": null,
    "conflicting_values": [],
    "prior_origins": [],
    "confirmed": false
  },
  "business_model": {
    "value": null,
    "state": "missing",
    "origin": null,
    "assumption_id": null,
    "conflicting_values": [],
    "prior_origins": [],
    "confirmed": false
  },
  "alternatives": {
    "value": null,
    "state": "missing",
    "origin": null,
    "assumption_id": null,
    "conflicting_values": [],
    "prior_origins": [],
    "confirmed": false
  },
  "constraints": {
    "customer": {
      "value": "Student",
      "state": "known",
      "origin": "user_stated",
      "assumption_id": null,
      "conflicting_values": [],
      "prior_origins": [],
      "confirmed": false
    }
  },
  "clarity_status": "broad_but_continue",
  "missing_fields": [],
  "clarifying_questions": [],
  "assumption_ids": [],
  "skipped_clarification": false,
  "continue_with_unknowns": false,
  "language_scope": [
    "tr"
  ],
  "primary_category": null,
  "category_origin": null,
  "category_confirmed": false,
  "add_on_packages": [],
  "secondary_categories": [],
  "modifiers": [],
  "category_rationale": null,
  "known_unknowns": []
};

export const raw: RawArtifact = {
  "schema_version": "1.0.0",
  "user_id": "10000000-0000-0000-0000-000000000001",
  "project_id": "10000000-0000-0000-0000-000000000001",
  "research_id": "10000000-0000-0000-0000-000000000001",
  "created_at": "2026-10-01T00:00:00Z",
  "versions": {
    "brief": 1,
    "plan": 1,
    "evidence_bundle": null,
    "category_catalog": null,
    "source_registry": null,
    "connectors": {
      "source-0017": "connector-v1"
    },
    "prompts": {
      "brief": "prompt-v1"
    },
    "model": null,
    "normalizer": null,
    "extractor": null,
    "decision_policy": null,
    "validator": null
  },
  "artifact_id": "10000000-0000-0000-0000-000000000001",
  "execution_id": "10000000-0000-0000-0000-000000000001",
  "query_id": "10000000-0000-0000-0000-000000000001",
  "source_id": "source-0017",
  "source_url": "https://example.org/item",
  "fetched_url": null,
  "collected_at": "2026-10-01T00:00:00Z",
  "published_at": null,
  "archive_captured_at": null,
  "license_or_restriction": null,
  "research_plan_version": 1,
  "access_method": "api",
  "artifact_origin": "live_capture",
  "content_kind": "discovery",
  "status": "succeeded",
  "body_ref": null,
  "content_hash": null,
  "byte_count": 0,
  "media_type": null,
  "connector_version": "connector-v1",
  "fields": {
    "title": "Discovered candidate",
    "author": null
  },
  "error": null
};

export const assessment: SufficiencyAssessment = {
  "status": "insufficient",
  "thesis": "Demand",
  "direction": "unknown",
  "independent_examples": 0,
  "independent_sources": 0,
  "minimum_examples": 3,
  "minimum_sources": 2,
  "qualitative_checks": {
    "market": "unknown"
  },
  "blocking_reasons": [
    "No customer evidence"
  ],
  "eligible_outcomes": [
    "investigate_more"
  ],
  "policy_version": "policy-v1"
};

// These invalid consumer values must remain rejected by the generated types.
// @ts-expect-error connector versions are strings
const invalidConnector: Versions["connectors"] = { "source-0017": 42 };
// @ts-expect-error qualitative check values are an exact status union
const invalidCheck: SufficiencyAssessment["qualitative_checks"] = { "market": "verified" };
void invalidConnector; void invalidCheck;
