// Generated by apps/api/scripts/generate_contracts.py. Do not edit.
import type { BriefContent, HumanBriefConfirm, HumanPlanPatch, PlanApprovalCreate, PlanDraftCreate, PlanMutationReceipt, PlanReference, PreparationAnalysis, PreparationAnalysisCreate, PreparationAnalysisOperation, PreparationAnalysisPage, RawArtifact, ResearchPlanPage, ResearchPlanPreparation, SufficiencyAssessment, Versions } from "../src/generated";

export const versions: Versions = {
  "brief": 1,
  "plan": 1,
  "evidence_bundle": null,
  "category_catalog": null,
  "source_registry": null,
  "connectors": {
    "source-0017": "connector-v1"
  },
  "prompts": {
    "brief": "prompt-v1"
  },
  "model": null,
  "normalizer": null,
  "extractor": null,
  "decision_policy": null,
  "validator": null
};

export const brief: BriefContent = {
  "original_idea": "Öğrenciler için not araması",
  "normalized_idea": null,
  "product_type": {
    "value": null,
    "state": "missing",
    "origin": null,
    "assumption_id": null,
    "conflicting_values": [],
    "prior_origins": [],
    "confirmed": false
  },
  "target_user": {
    "value": null,
    "state": "missing",
    "origin": null,
    "assumption_id": null,
    "conflicting_values": [],
    "prior_origins": [],
    "confirmed": false
  },
  "problem_or_job": {
    "value": null,
    "state": "missing",
    "origin": null,
    "assumption_id": null,
    "conflicting_values": [],
    "prior_origins": [],
    "confirmed": false
  },
  "context_or_niche": {
    "value": null,
    "state": "missing",
    "origin": null,
    "assumption_id": null,
    "conflicting_values": [],
    "prior_origins": [],
    "confirmed": false
  },
  "market_scope": {
    "value": null,
    "state": "missing",
    "origin": null,
    "assumption_id": null,
    "conflicting_values": [],
    "prior_origins": [],
    "confirmed": false
  },
  "business_model": {
    "value": null,
    "state": "missing",
    "origin": null,
    "assumption_id": null,
    "conflicting_values": [],
    "prior_origins": [],
    "confirmed": false
  },
  "alternatives": {
    "value": null,
    "state": "missing",
    "origin": null,
    "assumption_id": null,
    "conflicting_values": [],
    "prior_origins": [],
    "confirmed": false
  },
  "constraints": {
    "customer": {
      "value": "Student",
      "state": "known",
      "origin": "user_stated",
      "assumption_id": null,
      "conflicting_values": [],
      "prior_origins": [],
      "confirmed": false
    }
  },
  "clarity_status": "broad_but_continue",
  "missing_fields": [],
  "clarifying_questions": [],
  "assumption_ids": [],
  "skipped_clarification": false,
  "continue_with_unknowns": false,
  "language_scope": [
    "tr"
  ],
  "primary_category": null,
  "category_origin": null,
  "category_confirmed": false,
  "add_on_packages": [],
  "secondary_categories": [],
  "modifiers": [],
  "category_rationale": null,
  "known_unknowns": []
};

export const raw: RawArtifact = {
  "schema_version": "1.0.0",
  "user_id": "10000000-0000-0000-0000-000000000001",
  "project_id": "10000000-0000-0000-0000-000000000001",
  "research_id": "10000000-0000-0000-0000-000000000001",
  "created_at": "2026-10-01T00:00:00Z",
  "versions": {
    "brief": 1,
    "plan": 1,
    "evidence_bundle": null,
    "category_catalog": null,
    "source_registry": null,
    "connectors": {
      "source-0017": "connector-v1"
    },
    "prompts": {
      "brief": "prompt-v1"
    },
    "model": null,
    "normalizer": null,
    "extractor": null,
    "decision_policy": null,
    "validator": null
  },
  "artifact_id": "10000000-0000-0000-0000-000000000001",
  "execution_id": "10000000-0000-0000-0000-000000000001",
  "query_id": "10000000-0000-0000-0000-000000000001",
  "source_id": "source-0017",
  "source_url": "https://example.org/item",
  "fetched_url": null,
  "collected_at": "2026-10-01T00:00:00Z",
  "published_at": null,
  "archive_captured_at": null,
  "license_or_restriction": null,
  "research_plan_version": 1,
  "access_method": "api",
  "artifact_origin": "live_capture",
  "content_kind": "discovery",
  "status": "succeeded",
  "body_ref": null,
  "content_hash": null,
  "byte_count": 0,
  "media_type": null,
  "connector_version": "connector-v1",
  "fields": {
    "title": "Discovered candidate",
    "author": null
  },
  "error": null
};

export const assessment: SufficiencyAssessment = {
  "status": "insufficient",
  "thesis": "Demand",
  "direction": "unknown",
  "independent_examples": 0,
  "independent_sources": 0,
  "minimum_examples": 3,
  "minimum_sources": 2,
  "qualitative_checks": {
    "market": "unknown"
  },
  "blocking_reasons": [
    "No customer evidence"
  ],
  "eligible_outcomes": [
    "investigate_more"
  ],
  "policy_version": "policy-v1"
};

export const humanBriefConfirmation: HumanBriefConfirm = {
  "expected_brief_id": "10000000-0000-4000-8000-000000000002",
  "expected_brief_version": 1,
  "analysis_id": "10000000-0000-4000-8000-000000000003",
  "accepted_proposal_ids": [
    "field-target"
  ],
  "category_choice": "proposal",
  "category_proposal_id": "category-tool",
  "continue_with_unknowns": true
};

export const analysisCreate: PreparationAnalysisCreate = {
  "kind": "brief",
  "expected_brief_id": "10000000-0000-4000-8000-000000000002",
  "expected_brief_version": 1,
  "budget": {
    "max_requests": 300,
    "max_bytes": 50000000,
    "max_pages": 150,
    "max_records": 1000,
    "max_duration_seconds": 1800,
    "max_tokens": 300000,
    "max_cost_usd": "5.000000",
    "soft_cost_usd": "4.000000",
    "max_concurrency": 2
  }
};

export const preparationAnalysis: PreparationAnalysis = {
  "schema_version": "1.0.0",
  "user_id": "10000000-0000-0000-0000-000000000001",
  "project_id": "10000000-0000-0000-0000-000000000001",
  "research_id": "10000000-0000-0000-0000-000000000001",
  "created_at": "2026-10-02T00:00:00Z",
  "versions": {
    "brief": 1,
    "plan": null,
    "evidence_bundle": null,
    "category_catalog": null,
    "source_registry": null,
    "connectors": {},
    "prompts": {},
    "model": null,
    "normalizer": null,
    "extractor": null,
    "decision_policy": null,
    "validator": null
  },
  "analysis_id": "10000000-0000-4000-8000-000000000003",
  "analysis_kind": "brief",
  "input_brief_id": "10000000-0000-4000-8000-000000000002",
  "input_brief_version": 1,
  "input_plan_id": null,
  "input_plan_version": null,
  "input_plan_fingerprint": null,
  "field_proposals": [
    {
      "proposal_id": "field-target",
      "field_path": "target_user",
      "value": "Öğrenciler 🙂",
      "origin": "ai_hypothesis",
      "assumption_id": "assumption-target",
      "basis_refs": [
        "original_idea"
      ]
    }
  ],
  "normalized_idea": null,
  "category_proposal": {
    "proposal_id": "category-tool",
    "primary_category": "gelistirici-araci",
    "rationale": "A proposed label requires human confirmation.",
    "secondary_categories": [],
    "add_on_packages": [],
    "modifiers": []
  },
  "clarifying_questions": [
    "Hangi kullanıcı için?"
  ],
  "missing_fields": [
    "market_scope"
  ],
  "known_unknowns": [
    "Pazar bilinmiyor"
  ],
  "intent_proposals": [
    {
      "proposal_id": "intent-problem",
      "intent": "problem_demand",
      "question": "Not araması zor mu?",
      "priority": 1,
      "brief_basis": [
        "original_idea"
      ],
      "expected_fields": [
        "text"
      ],
      "required_evidence_types": [
        "direct_experience"
      ],
      "validation_kind": "investigate_secondary",
      "included": true,
      "exclusion_reason": null
    }
  ],
  "query_hypotheses": [
    {
      "proposal_id": "query-problem",
      "intent_proposal_id": "intent-problem",
      "query_text": "öğrenci not araması şikayet 🙂",
      "language": "tr",
      "market_scope": null,
      "origin": "ai_hypothesis",
      "basis_refs": [
        "original_idea"
      ]
    }
  ]
};

export const analysisOperation: PreparationAnalysisOperation = {
  "schema_version": "1.0.0",
  "user_id": "10000000-0000-0000-0000-000000000001",
  "project_id": "10000000-0000-0000-0000-000000000001",
  "research_id": "10000000-0000-0000-0000-000000000001",
  "operation": "analyze_brief",
  "request_key": "10000000-0000-0000-0000-000000000001",
  "input_fingerprint": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "analysis_id": "10000000-0000-4000-8000-000000000003",
  "attempt_id": "10000000-0000-4000-8000-000000000005",
  "input_brief_id": "10000000-0000-4000-8000-000000000002",
  "input_brief_version": 1,
  "input_plan_id": null,
  "input_plan_version": null,
  "input_plan_fingerprint": null,
  "status": "completed",
  "analysis": {
    "schema_version": "1.0.0",
    "user_id": "10000000-0000-0000-0000-000000000001",
    "project_id": "10000000-0000-0000-0000-000000000001",
    "research_id": "10000000-0000-0000-0000-000000000001",
    "created_at": "2026-10-02T00:00:00Z",
    "versions": {
      "brief": 1,
      "plan": null,
      "evidence_bundle": null,
      "category_catalog": null,
      "source_registry": null,
      "connectors": {},
      "prompts": {},
      "model": null,
      "normalizer": null,
      "extractor": null,
      "decision_policy": null,
      "validator": null
    },
    "analysis_id": "10000000-0000-4000-8000-000000000003",
    "analysis_kind": "brief",
    "input_brief_id": "10000000-0000-4000-8000-000000000002",
    "input_brief_version": 1,
    "input_plan_id": null,
    "input_plan_version": null,
    "input_plan_fingerprint": null,
    "field_proposals": [
      {
        "proposal_id": "field-target",
        "field_path": "target_user",
        "value": "Öğrenciler 🙂",
        "origin": "ai_hypothesis",
        "assumption_id": "assumption-target",
        "basis_refs": [
          "original_idea"
        ]
      }
    ],
    "normalized_idea": null,
    "category_proposal": {
      "proposal_id": "category-tool",
      "primary_category": "gelistirici-araci",
      "rationale": "A proposed label requires human confirmation.",
      "secondary_categories": [],
      "add_on_packages": [],
      "modifiers": []
    },
    "clarifying_questions": [
      "Hangi kullanıcı için?"
    ],
    "missing_fields": [
      "market_scope"
    ],
    "known_unknowns": [
      "Pazar bilinmiyor"
    ],
    "intent_proposals": [
      {
        "proposal_id": "intent-problem",
        "intent": "problem_demand",
        "question": "Not araması zor mu?",
        "priority": 1,
        "brief_basis": [
          "original_idea"
        ],
        "expected_fields": [
          "text"
        ],
        "required_evidence_types": [
          "direct_experience"
        ],
        "validation_kind": "investigate_secondary",
        "included": true,
        "exclusion_reason": null
      }
    ],
    "query_hypotheses": [
      {
        "proposal_id": "query-problem",
        "intent_proposal_id": "intent-problem",
        "query_text": "öğrenci not araması şikayet 🙂",
        "language": "tr",
        "market_scope": null,
        "origin": "ai_hypothesis",
        "basis_refs": [
          "original_idea"
        ]
      }
    ]
  },
  "usage": {
    "requests": 1,
    "bytes": 0,
    "pages": 0,
    "records": 0,
    "duration_seconds": 0.0,
    "input_tokens": 100,
    "output_tokens": 50,
    "cost_usd": "0.000100",
    "reserved_cost_usd": "0.000000",
    "provider_result_unknown": false
  },
  "created_at": "2026-10-02T00:00:00Z",
  "current_scope_matches": true
};

export const analysisPage: PreparationAnalysisPage = {
  "schema_version": "1.0.0",
  "items": [
    {
      "schema_version": "1.0.0",
      "user_id": "10000000-0000-0000-0000-000000000001",
      "project_id": "10000000-0000-0000-0000-000000000001",
      "research_id": "10000000-0000-0000-0000-000000000001",
      "created_at": "2026-10-02T00:00:00Z",
      "versions": {
        "brief": 1,
        "plan": null,
        "evidence_bundle": null,
        "category_catalog": null,
        "source_registry": null,
        "connectors": {},
        "prompts": {},
        "model": null,
        "normalizer": null,
        "extractor": null,
        "decision_policy": null,
        "validator": null
      },
      "analysis_id": "10000000-0000-4000-8000-000000000003",
      "analysis_kind": "brief",
      "input_brief_id": "10000000-0000-4000-8000-000000000002",
      "input_brief_version": 1,
      "input_plan_id": null,
      "input_plan_version": null,
      "input_plan_fingerprint": null,
      "field_proposals": [
        {
          "proposal_id": "field-target",
          "field_path": "target_user",
          "value": "Öğrenciler 🙂",
          "origin": "ai_hypothesis",
          "assumption_id": "assumption-target",
          "basis_refs": [
            "original_idea"
          ]
        }
      ],
      "normalized_idea": null,
      "category_proposal": {
        "proposal_id": "category-tool",
        "primary_category": "gelistirici-araci",
        "rationale": "A proposed label requires human confirmation.",
        "secondary_categories": [],
        "add_on_packages": [],
        "modifiers": []
      },
      "clarifying_questions": [
        "Hangi kullanıcı için?"
      ],
      "missing_fields": [
        "market_scope"
      ],
      "known_unknowns": [
        "Pazar bilinmiyor"
      ],
      "intent_proposals": [
        {
          "proposal_id": "intent-problem",
          "intent": "problem_demand",
          "question": "Not araması zor mu?",
          "priority": 1,
          "brief_basis": [
            "original_idea"
          ],
          "expected_fields": [
            "text"
          ],
          "required_evidence_types": [
            "direct_experience"
          ],
          "validation_kind": "investigate_secondary",
          "included": true,
          "exclusion_reason": null
        }
      ],
      "query_hypotheses": [
        {
          "proposal_id": "query-problem",
          "intent_proposal_id": "intent-problem",
          "query_text": "öğrenci not araması şikayet 🙂",
          "language": "tr",
          "market_scope": null,
          "origin": "ai_hypothesis",
          "basis_refs": [
            "original_idea"
          ]
        }
      ]
    }
  ],
  "page": {
    "next_cursor": null,
    "limit": 25
  }
};

export const planDraftCreate: PlanDraftCreate = {
  "expected_brief_id": "10000000-0000-4000-8000-000000000002",
  "expected_brief_version": 2,
  "analysis_id": "10000000-0000-4000-8000-000000000003",
  "research_mode": "standard",
  "budget": {
    "max_requests": 300,
    "max_bytes": 50000000,
    "max_pages": 150,
    "max_records": 1000,
    "max_duration_seconds": 1800,
    "max_tokens": 300000,
    "max_cost_usd": "5.000000",
    "soft_cost_usd": "4.000000",
    "max_concurrency": 2
  }
};

export const humanPlanPatch: HumanPlanPatch = {
  "expected_plan_id": "10000000-0000-4000-8000-000000000004",
  "expected_plan_version": 1,
  "expected_plan_fingerprint": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
  "expected_brief_id": "10000000-0000-4000-8000-000000000002",
  "expected_brief_version": 2,
  "excluded_query_ids": []
};

export const planApprovalCreate: PlanApprovalCreate = {
  "expected_plan_id": "10000000-0000-4000-8000-000000000004",
  "expected_plan_version": 1,
  "expected_plan_fingerprint": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
  "expected_brief_id": "10000000-0000-4000-8000-000000000002",
  "expected_brief_version": 2
};

export const planReference: PlanReference = {
  "research_plan_id": "10000000-0000-4000-8000-000000000004",
  "plan_version": 1,
  "plan_fingerprint": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
  "status": "awaiting_user",
  "brief_id": "10000000-0000-4000-8000-000000000002",
  "brief_version": 2,
  "created_at": "2026-10-02T00:00:00Z"
};

export const planPage: ResearchPlanPage = {
  "schema_version": "1.0.0",
  "items": [
    {
      "schema_version": "1.0.0",
      "user_id": "10000000-0000-0000-0000-000000000001",
      "project_id": "10000000-0000-0000-0000-000000000001",
      "research_id": "10000000-0000-0000-0000-000000000001",
      "created_at": "2026-10-02T00:00:00Z",
      "versions": {
        "brief": 2,
        "plan": 1,
        "evidence_bundle": null,
        "category_catalog": null,
        "source_registry": null,
        "connectors": {},
        "prompts": {},
        "model": null,
        "normalizer": null,
        "extractor": null,
        "decision_policy": null,
        "validator": null
      },
      "research_plan_id": "10000000-0000-4000-8000-000000000004",
      "plan_version": 1,
      "plan_fingerprint": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      "status": "awaiting_user",
      "brief_id": "10000000-0000-4000-8000-000000000002",
      "brief_version": 2,
      "brief": {
        "original_idea": "  Öğrenciler için not araması\n🙂 aynen korunur  ",
        "normalized_idea": null,
        "product_type": {
          "value": null,
          "state": "missing",
          "origin": null,
          "assumption_id": null,
          "conflicting_values": [],
          "prior_origins": [],
          "confirmed": false
        },
        "target_user": {
          "value": null,
          "state": "missing",
          "origin": null,
          "assumption_id": null,
          "conflicting_values": [],
          "prior_origins": [],
          "confirmed": false
        },
        "problem_or_job": {
          "value": null,
          "state": "missing",
          "origin": null,
          "assumption_id": null,
          "conflicting_values": [],
          "prior_origins": [],
          "confirmed": false
        },
        "context_or_niche": {
          "value": null,
          "state": "missing",
          "origin": null,
          "assumption_id": null,
          "conflicting_values": [],
          "prior_origins": [],
          "confirmed": false
        },
        "market_scope": {
          "value": null,
          "state": "missing",
          "origin": null,
          "assumption_id": null,
          "conflicting_values": [],
          "prior_origins": [],
          "confirmed": false
        },
        "business_model": {
          "value": null,
          "state": "missing",
          "origin": null,
          "assumption_id": null,
          "conflicting_values": [],
          "prior_origins": [],
          "confirmed": false
        },
        "alternatives": {
          "value": null,
          "state": "missing",
          "origin": null,
          "assumption_id": null,
          "conflicting_values": [],
          "prior_origins": [],
          "confirmed": false
        },
        "constraints": {},
        "clarity_status": "broad_but_continue",
        "missing_fields": [],
        "clarifying_questions": [],
        "assumption_ids": [],
        "skipped_clarification": false,
        "continue_with_unknowns": true,
        "language_scope": [
          "tr"
        ],
        "primary_category": "gelistirici-araci",
        "category_origin": "user_confirmed",
        "category_confirmed": true,
        "add_on_packages": [],
        "secondary_categories": [],
        "modifiers": [],
        "category_rationale": null,
        "known_unknowns": [
          "Current source permission unavailable"
        ]
      },
      "research_mode": "standard",
      "intents": [],
      "source_plan": [],
      "query_plan": [],
      "budget": {
        "max_requests": 300,
        "max_bytes": 50000000,
        "max_pages": 150,
        "max_records": 1000,
        "max_duration_seconds": 1800,
        "max_tokens": 300000,
        "max_cost_usd": "5.000000",
        "soft_cost_usd": "4.000000",
        "max_concurrency": 2
      },
      "known_unknowns": [
        "No current qualified source"
      ],
      "confirmed_at": null
    }
  ],
  "page": {
    "next_cursor": null,
    "limit": 25
  }
};

export const planPreparation: ResearchPlanPreparation = {
  "schema_version": "1.0.0",
  "user_id": "10000000-0000-0000-0000-000000000001",
  "project_id": "10000000-0000-0000-0000-000000000001",
  "research_id": "10000000-0000-0000-0000-000000000001",
  "plan": {
    "schema_version": "1.0.0",
    "user_id": "10000000-0000-0000-0000-000000000001",
    "project_id": "10000000-0000-0000-0000-000000000001",
    "research_id": "10000000-0000-0000-0000-000000000001",
    "created_at": "2026-10-02T00:00:00Z",
    "versions": {
      "brief": 2,
      "plan": 1,
      "evidence_bundle": null,
      "category_catalog": null,
      "source_registry": null,
      "connectors": {},
      "prompts": {},
      "model": null,
      "normalizer": null,
      "extractor": null,
      "decision_policy": null,
      "validator": null
    },
    "research_plan_id": "10000000-0000-4000-8000-000000000004",
    "plan_version": 1,
    "plan_fingerprint": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    "status": "awaiting_user",
    "brief_id": "10000000-0000-4000-8000-000000000002",
    "brief_version": 2,
    "brief": {
      "original_idea": "  Öğrenciler için not araması\n🙂 aynen korunur  ",
      "normalized_idea": null,
      "product_type": {
        "value": null,
        "state": "missing",
        "origin": null,
        "assumption_id": null,
        "conflicting_values": [],
        "prior_origins": [],
        "confirmed": false
      },
      "target_user": {
        "value": null,
        "state": "missing",
        "origin": null,
        "assumption_id": null,
        "conflicting_values": [],
        "prior_origins": [],
        "confirmed": false
      },
      "problem_or_job": {
        "value": null,
        "state": "missing",
        "origin": null,
        "assumption_id": null,
        "conflicting_values": [],
        "prior_origins": [],
        "confirmed": false
      },
      "context_or_niche": {
        "value": null,
        "state": "missing",
        "origin": null,
        "assumption_id": null,
        "conflicting_values": [],
        "prior_origins": [],
        "confirmed": false
      },
      "market_scope": {
        "value": null,
        "state": "missing",
        "origin": null,
        "assumption_id": null,
        "conflicting_values": [],
        "prior_origins": [],
        "confirmed": false
      },
      "business_model": {
        "value": null,
        "state": "missing",
        "origin": null,
        "assumption_id": null,
        "conflicting_values": [],
        "prior_origins": [],
        "confirmed": false
      },
      "alternatives": {
        "value": null,
        "state": "missing",
        "origin": null,
        "assumption_id": null,
        "conflicting_values": [],
        "prior_origins": [],
        "confirmed": false
      },
      "constraints": {},
      "clarity_status": "broad_but_continue",
      "missing_fields": [],
      "clarifying_questions": [],
      "assumption_ids": [],
      "skipped_clarification": false,
      "continue_with_unknowns": true,
      "language_scope": [
        "tr"
      ],
      "primary_category": "gelistirici-araci",
      "category_origin": "user_confirmed",
      "category_confirmed": true,
      "add_on_packages": [],
      "secondary_categories": [],
      "modifiers": [],
      "category_rationale": null,
      "known_unknowns": [
        "Current source permission unavailable"
      ]
    },
    "research_mode": "standard",
    "intents": [],
    "source_plan": [],
    "query_plan": [],
    "budget": {
      "max_requests": 300,
      "max_bytes": 50000000,
      "max_pages": 150,
      "max_records": 1000,
      "max_duration_seconds": 1800,
      "max_tokens": 300000,
      "max_cost_usd": "5.000000",
      "soft_cost_usd": "4.000000",
      "max_concurrency": 2
    },
    "known_unknowns": [
      "No current qualified source"
    ],
    "confirmed_at": null
  },
  "is_latest": true,
  "current_brief": {
    "brief_id": "10000000-0000-4000-8000-000000000002",
    "brief_version": 2,
    "status": "confirmed",
    "created_at": "2026-10-02T00:00:00Z"
  },
  "eligibility": {
    "can_approve": false,
    "can_start": false,
    "blocking_reasons": [
      "no_eligible_source"
    ],
    "coverage_gaps": [],
    "qualification_version": null,
    "qualification_digest": null,
    "checked_at": "2026-10-02T00:00:00Z",
    "valid_until": null
  }
};

export const planMutationReceipt: PlanMutationReceipt = {
  "schema_version": "1.0.0",
  "user_id": "10000000-0000-0000-0000-000000000001",
  "project_id": "10000000-0000-0000-0000-000000000001",
  "research_id": "10000000-0000-0000-0000-000000000001",
  "operation": "draft_plan",
  "request_key": "10000000-0000-0000-0000-000000000001",
  "input_fingerprint": "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
  "input_brief_id": "10000000-0000-4000-8000-000000000002",
  "input_brief_version": 2,
  "input_plan_id": null,
  "input_plan_version": null,
  "input_plan_fingerprint": null,
  "result_plan_id": "10000000-0000-4000-8000-000000000004",
  "result_plan_version": 1,
  "result_plan_fingerprint": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
  "created_at": "2026-10-02T00:00:00Z",
  "plan": {
    "schema_version": "1.0.0",
    "user_id": "10000000-0000-0000-0000-000000000001",
    "project_id": "10000000-0000-0000-0000-000000000001",
    "research_id": "10000000-0000-0000-0000-000000000001",
    "created_at": "2026-10-02T00:00:00Z",
    "versions": {
      "brief": 2,
      "plan": 1,
      "evidence_bundle": null,
      "category_catalog": null,
      "source_registry": null,
      "connectors": {},
      "prompts": {},
      "model": null,
      "normalizer": null,
      "extractor": null,
      "decision_policy": null,
      "validator": null
    },
    "research_plan_id": "10000000-0000-4000-8000-000000000004",
    "plan_version": 1,
    "plan_fingerprint": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    "status": "awaiting_user",
    "brief_id": "10000000-0000-4000-8000-000000000002",
    "brief_version": 2,
    "brief": {
      "original_idea": "  Öğrenciler için not araması\n🙂 aynen korunur  ",
      "normalized_idea": null,
      "product_type": {
        "value": null,
        "state": "missing",
        "origin": null,
        "assumption_id": null,
        "conflicting_values": [],
        "prior_origins": [],
        "confirmed": false
      },
      "target_user": {
        "value": null,
        "state": "missing",
        "origin": null,
        "assumption_id": null,
        "conflicting_values": [],
        "prior_origins": [],
        "confirmed": false
      },
      "problem_or_job": {
        "value": null,
        "state": "missing",
        "origin": null,
        "assumption_id": null,
        "conflicting_values": [],
        "prior_origins": [],
        "confirmed": false
      },
      "context_or_niche": {
        "value": null,
        "state": "missing",
        "origin": null,
        "assumption_id": null,
        "conflicting_values": [],
        "prior_origins": [],
        "confirmed": false
      },
      "market_scope": {
        "value": null,
        "state": "missing",
        "origin": null,
        "assumption_id": null,
        "conflicting_values": [],
        "prior_origins": [],
        "confirmed": false
      },
      "business_model": {
        "value": null,
        "state": "missing",
        "origin": null,
        "assumption_id": null,
        "conflicting_values": [],
        "prior_origins": [],
        "confirmed": false
      },
      "alternatives": {
        "value": null,
        "state": "missing",
        "origin": null,
        "assumption_id": null,
        "conflicting_values": [],
        "prior_origins": [],
        "confirmed": false
      },
      "constraints": {},
      "clarity_status": "broad_but_continue",
      "missing_fields": [],
      "clarifying_questions": [],
      "assumption_ids": [],
      "skipped_clarification": false,
      "continue_with_unknowns": true,
      "language_scope": [
        "tr"
      ],
      "primary_category": "gelistirici-araci",
      "category_origin": "user_confirmed",
      "category_confirmed": true,
      "add_on_packages": [],
      "secondary_categories": [],
      "modifiers": [],
      "category_rationale": null,
      "known_unknowns": [
        "Current source permission unavailable"
      ]
    },
    "research_mode": "standard",
    "intents": [],
    "source_plan": [],
    "query_plan": [],
    "budget": {
      "max_requests": 300,
      "max_bytes": 50000000,
      "max_pages": 150,
      "max_records": 1000,
      "max_duration_seconds": 1800,
      "max_tokens": 300000,
      "max_cost_usd": "5.000000",
      "soft_cost_usd": "4.000000",
      "max_concurrency": 2
    },
    "known_unknowns": [
      "No current qualified source"
    ],
    "confirmed_at": null
  }
};

// These invalid consumer values must remain rejected by the generated types.
// @ts-expect-error connector versions are strings
const invalidConnector: Versions["connectors"] = { "source-0017": 42 };
// @ts-expect-error qualitative check values are an exact status union
const invalidCheck: SufficiencyAssessment["qualitative_checks"] = { "market": "verified" };
void invalidConnector; void invalidCheck;
