import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createBriefRevisionStore, createBriefRevisionResources, validateHumanBriefPatch } from '../lib/preparation/brief-revision-store.ts';
import { createPreparationStore } from '../lib/preparation/preparation-store.ts';
import { createApiClient } from '../lib/api/client.ts';
import { createSessionStore } from '../lib/auth/session-store.ts';
import { brief as content, versions } from '../../../packages/contracts/tests/producer-consumer.ts';
const owner='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002';
const project='00000000-0000-4000-8000-000000000010',research='00000000-0000-4000-8000-000000000011',briefId='00000000-0000-4000-8000-000000000012',key='00000000-0000-4000-8000-000000000013';
const date='2026-10-02T00:00:00Z',csrf='a'.repeat(64),idea='  Immutable 😀\n\uFEFF ',patch={expected_brief_version:1,target_user:'  Teams 😀\uFEFF '};
const session=(id=owner,token=csrf,expiry=Date.now()+60000)=>({schema_version:'1.0.0',user:{schema_version:'1.0.0',user_id:id,email:'synthetic@example.test',created_at:date},csrf_token:token,expires_at:new Date(expiry).toISOString()});
const base=(extra={})=>({schema_version:'1.0.0',user_id:owner,project_id:project,research_id:research,brief_id:briefId,brief_version:1,created_at:date,versions:{...versions,brief:1,plan:null},status:'awaiting_user',content:{...structuredClone(content),original_idea:idea,constraints:{},clarity_status:'needs_clarification',language_scope:['tr'],skipped_clarification:false,continue_with_unknowns:false},...extra});
const changed=value=>({value,state:value===null?'missing':'known',origin:value===null?null:'user_stated',confirmed:false,assumption_id:null,prior_origins:[],conflicting_values:[]});
function revised(input=patch,extra={}){const result=base({brief_version:input.expected_brief_version+1,versions:{...versions,brief:input.expected_brief_version+1,plan:null}});for(const name of ['product_type','target_user','problem_or_job','context_or_niche','market_scope','business_model','alternatives'])if(Object.hasOwn(input,name))result.content[name]=changed(input[name]);for(const [name,value]of Object.entries(input.constraints??{}))result.content.constraints[name]=changed(value);for(const name of ['language_scope','modifiers','skipped_clarification','continue_with_unknowns'])if(Object.hasOwn(input,name))result.content[name]=input[name];if(Object.hasOwn(input,'primary_category'))Object.assign(result.content,{primary_category:input.primary_category,category_origin:input.primary_category===null?null:'user_stated',category_confirmed:false,category_rationale:null});return {...result,...extra};}
const receipt=(extra={})=>({schema_version:'1.0.0',operation:'revise_brief',request_key:key,input_fingerprint:'b'.repeat(64),user_id:owner,project_id:project,research_id:research,brief_id:briefId,brief_version:2,created_at:date,brief:revised(),...extra});
const error=(retry=null)=>({schema_version:'1.0.0',code:'request_failed',message:'Private server text',request_id:other,operation:null,stage:null,query_id:null,details_ref:null,source_id:null,retryable:true,retry_after_seconds:retry,usage:null,remaining_work:[],next_step:null});
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
function fixture(t,fetcher,now,invalidate,makeKey=()=>key){const store=createBriefRevisionStore(createApiClient(fetcher),now,invalidate,makeKey);t.after(()=>store.dispose());store.bindSession(session());store.select(project,research);store.observeLatest(base());store.setInput(patch);return store;}

test('canonical sparse null/false/empty dictionaries/lists and raw Unicode are distinct without defaults',()=>{
 for(const input of [patch,{expected_brief_version:1,target_user:null},{expected_brief_version:1,constraints:{budget:null,'\uFEFF':'😀'.repeat(10000)}},{expected_brief_version:1,modifiers:[]},{expected_brief_version:1,continue_with_unknowns:false},{expected_brief_version:1,primary_category:null}])assert.equal(validateHumanBriefPatch(input),true);
 for(const input of [{expected_brief_version:1},{expected_brief_version:true,target_user:'x'},{expected_brief_version:'1',target_user:'x'},{expected_brief_version:new Number(1),target_user:'x'},{expected_brief_version:1.1,target_user:'x'},{expected_brief_version:0,target_user:'x'},{expected_brief_version:2147483648,target_user:'x'},{...patch,original_idea:idea},{...patch,user_id:owner},{...patch,constraints:null},{...patch,constraints:{'\u0085':'x'}},{...patch,constraints:{budget:12}},{...patch,language_scope:null},{...patch,language_scope:[]},{...patch,language_scope:['tr','tr']},{...patch,modifiers:['x','x']},{...patch,continue_with_unknowns:null},{...patch,continue_with_unknowns:1},{...patch,target_user:'😀'.repeat(10001)},{...patch,target_user:'\ud800'},{...patch,target_user:'\u0085'},{...patch,primary_category:'invented'}])assert.equal(validateHumanBriefPatch(input),false);
});

test('POST captures sparse body/owner/research/CSRF/UUID before pending and suppresses double send',async t=>{let release,allocated=0;const calls=[],original=session();const store=fixture(t,async(path,init)=>{calls.push([path,init]);return new Promise(resolve=>release=()=>resolve(json(revised(),201)));},undefined,undefined,()=>{allocated++;return key;});store.bindSession(original);const unsubscribe=store.subscribe(()=>{if(store.getSnapshot().status==='pending'){original.csrf_token='c'.repeat(64);original.user.user_id=other;store.getSnapshot().input.target_user='mutated';}});t.after(unsubscribe);const operation=store.reviseBrief();assert.equal(await store.reviseBrief(),false);assert.equal(calls.length,1);assert.equal(allocated,1);assert.equal(calls[0][0],`/api/backend/api/v1/projects/${project}/research/${research}/briefs`);assert.equal(calls[0][1].body,JSON.stringify(patch));assert.equal(calls[0][1].headers['Idempotency-Key'],key);assert.equal(calls[0][1].headers['X-CSRF-Token'],csrf);assert.equal(calls[0][1].credentials,'same-origin');assert.equal(calls[0][1].cache,'no-store');release();assert.equal(await operation,true);for(const name of ['key','csrfToken','raw'])assert.equal(Object.hasOwn(store.getSnapshot(),name),false);});

test('nullable constraints and omission are sent untouched with no language default',async t=>{const input={expected_brief_version:1,target_user:null,constraints:{budget:null,scope:'  Unicode 😀\uFEFF '},primary_category:null,modifiers:[],continue_with_unknowns:false};let sent;const store=fixture(t,async(_path,init)=>{sent=init.body;return json(revised(input),201);});store.setInput(input);assert.equal(await store.reviseBrief(),true);assert.deepEqual(JSON.parse(sent),input);assert.equal(Object.hasOwn(JSON.parse(sent),'language_scope'),false);});

test('anonymous expired malformed identity/scope, unknown fields/version and no edit cannot send',async t=>{let calls=0;const store=fixture(t,async()=>{calls++;return json(revised(),201);});assert.equal(store.setInput({...patch,original_idea:'changed'}),false);assert.equal(store.setInput({...patch,expected_brief_version:2}),false);store.setInput({expected_brief_version:1});assert.equal(await store.reviseBrief(),false);for(const value of [null,session(owner,csrf,Date.now()-1),{...session(),csrf_token:[csrf]}]){store.bindSession(value);assert.equal(await store.reviseBrief(),false);}store.bindSession(session());for(const args of [[project,'../bad'],[null,research],[project,[research]]]){assert.equal(store.select(...args),false);assert.equal(await store.reviseBrief(),false);}assert.equal(calls,0);});

test('historical selection hides editor and blocks writes while preserving unknown capture',async t=>{let calls=0;const store=fixture(t,async()=>{calls++;return json(error(),503);});await store.reviseBrief();store.observeLatest(null);assert.equal(store.getSnapshot().input,null);assert.equal(await store.resolveRevision(),false);assert.equal(await store.replayRevision(patch),false);store.observeLatest(base());assert.equal(store.getSnapshot().status,'unknown');assert.deepEqual(store.getSnapshot().input,patch);assert.equal(calls,1);});

test('network malformed success and5xx keep unknown with no autoGET/retry/replacement key',async t=>{for(const response of [()=>{throw Error('private');},()=>json(error(),503),()=>json({},201),()=>new Response('private HTML',{status:201})]){let calls=0,keys=0;const store=fixture(t,async()=>{calls++;return response();},undefined,undefined,()=>{keys++;return key;});await store.reviseBrief();assert.equal(store.getSnapshot().status,'unknown');assert.equal(store.setInput({...patch,target_user:'changed'}),false);assert.equal(await store.reviseBrief(),false);assert.equal(store.redraft(base()),false);await new Promise(r=>setTimeout(r,5));assert.equal(calls,1);assert.equal(keys,1);assert.ok(!store.getSnapshot().message.includes('private'));}});

test('404 receipt stays unknown; exact replay retains UUID/body and expected version',async t=>{const calls=[];let keys=0;const store=fixture(t,async(path,init)=>{calls.push([path,init]);return calls.length===1?json(error(),503):calls.length===2?json(error(),404):json(revised(),200);},undefined,undefined,()=>{keys++;return key;});await store.reviseBrief();assert.equal(await store.resolveRevision(),false);assert.equal(store.getSnapshot().status,'unknown');assert.ok(store.getSnapshot().message.includes('may still commit'));assert.equal(await store.replayRevision({...patch,target_user:'new'}),false);assert.equal(await store.replayRevision({...patch,expected_brief_version:2}),false);assert.equal(await store.replayRevision(patch),true);assert.equal(keys,1);assert.equal(calls[1][0],`/api/backend/api/v1/projects/${project}/preparation-mutations/revise_brief/${key}`);assert.equal(calls[1][1].method,'GET');assert.equal(calls[1][1].body,undefined);assert.equal(calls[1][1].headers['X-CSRF-Token'],undefined);assert.equal(calls[0][1].body,calls[2][1].body);assert.equal(calls[0][1].headers['Idempotency-Key'],calls[2][1].headers['Idempotency-Key']);});

test('receipt and replay deduplicate concurrent actions',async t=>{let release,count=0;const store=fixture(t,async()=>++count===1?json(error(),503):new Promise(resolve=>release=()=>resolve(json(receipt()))));await store.reviseBrief();const pending=store.resolveRevision();assert.equal(await store.resolveRevision(),false);assert.equal(await store.replayRevision(patch),false);release();assert.equal(await pending,true);assert.equal(count,2);});

test('receipt validates op/key/tenant/research/nested identity/version/original/schema',async t=>{for(const value of [receipt({operation:'create_research'}),receipt({request_key:other}),receipt({user_id:other}),receipt({project_id:other}),receipt({research_id:other}),receipt({brief_id:other}),receipt({brief_version:3}),receipt({brief:revised(patch,{brief_version:3,versions:{...versions,brief:3,plan:null}})}),receipt({brief:revised(patch,{content:{...revised().content,original_idea:'changed'}})}),receipt({private:'extra'}),receipt({schema_version:'2.0.0'})]){let count=0;const store=fixture(t,async()=>++count===1?json(error(),503):json(value));await store.reviseBrief();assert.equal(await store.resolveRevision(),false);assert.equal(store.getSnapshot().status,'unknown');assert.equal(store.getSnapshot().saved,null);}});

test('POST rejects wrong identity/status/version/provenance/sent values',async t=>{for(const [value,status]of [[revised(patch,{user_id:other}),201],[revised(patch,{research_id:other}),201],[revised(patch,{brief_id:other}),201],[revised(patch,{brief_version:3,versions:{...versions,brief:3,plan:null}}),201],[revised(patch,{status:'confirmed'}),201],[revised(patch,{versions:{...versions,brief:null,plan:null}}),201],[revised({expected_brief_version:1,target_user:null}),201],[revised(patch,{content:{...revised().content,target_user:{...changed(patch.target_user),confirmed:true}}}),201],[revised(),202]]){const store=fixture(t,async()=>json(value,status));assert.equal(await store.reviseBrief(),false);assert.equal(store.getSnapshot().status,'unknown');}});

test('409 requires fresh observed latest and explicit redraft; no implicit version rewrite',async t=>{let calls=0;const store=fixture(t,async()=>{calls++;return json(error(),409);});await store.reviseBrief();assert.equal(store.getSnapshot().status,'conflict');assert.equal(store.getSnapshot().input.expected_brief_version,1);assert.equal(store.redraft(base()),false);assert.equal(await store.reviseBrief(),false);assert.equal(store.setInput({...patch,expected_brief_version:2}),false);const latest=base({brief_version:2,versions:{...versions,brief:2,plan:null}});store.observeLatest(latest);assert.equal(store.getSnapshot().input.expected_brief_version,1);assert.equal(store.redraft(base()),false);assert.equal(store.redraft(latest),true);assert.deepEqual(store.getSnapshot().input,{expected_brief_version:2});assert.equal(calls,1);});

test('409 on replay remains unknown and cannot allocate new draft',async t=>{let calls=0;const store=fixture(t,async()=>json(error(),++calls===1?503:409));await store.reviseBrief();await store.replayRevision(patch);assert.equal(store.getSnapshot().status,'unknown');store.observeLatest(base({brief_version:3,versions:{...versions,brief:3,plan:null}}));assert.equal(store.redraft(base()),false);assert.equal(await store.reviseBrief(),false);assert.equal(calls,2);});

test('historical receipt never overwrites separately selected current brief or old captured input',async t=>{const latest=base({brief_version:3,versions:{...versions,brief:3,plan:null}});const reads=createPreparationStore(createApiClient(async()=>json(latest)));t.after(()=>reads.dispose());reads.bindSession(session());reads.select(project,research);await reads.getLatestBrief();const selected=reads.getSnapshot();let calls=0;const store=fixture(t,async()=>++calls===1?json(error(),503):json(receipt()));await store.reviseBrief();store.observeLatest(latest);assert.equal(await store.resolveRevision(),true);assert.equal(reads.getSnapshot(),selected);assert.equal(store.getSnapshot().base.brief_version,1);assert.equal(store.getSnapshot().saved.brief_version,2);});

test('input tampering blocks receipt and replay',async t=>{let calls=0;const store=fixture(t,async()=>{calls++;return json(error(),503);});await store.reviseBrief();store.getSnapshot().input.target_user='tampered';assert.equal(await store.resolveRevision(),false);assert.equal(await store.replayRevision(patch),false);assert.equal(calls,1);});

test('owner/token/logout/project/research/disposal aborts and drops late private data',async t=>{for(const change of [s=>s.bindSession(null),s=>s.bindSession(session(other,'b'.repeat(64))),s=>s.bindSession(session(owner,'b'.repeat(64))),s=>s.select(other,research),s=>s.select(project,other),s=>s.dispose()]){let release,signal;const store=fixture(t,async(_path,init)=>{signal=init.signal;return new Promise(resolve=>release=()=>resolve(json(revised(),201)));});const pending=store.reviseBrief();change(store);const current=store.getSnapshot();assert.equal(signal.aborted,true);release();assert.equal(await pending,false);assert.equal(store.getSnapshot(),current);assert.equal(store.getSnapshot().input,null);}});

test('subscriber scope change aborts before captured request is sent',async t=>{let calls=0;const store=fixture(t,async()=>{calls++;return json(revised(),201);});const unsubscribe=store.subscribe(()=>{if(store.getSnapshot().status==='pending')store.select(project,other);});t.after(unsubscribe);assert.equal(await store.reviseBrief(),false);assert.equal(calls,0);});

test('suspend hides/aborts unknown then matching owner+CSRF restores exact replay',async t=>{let release,calls=0;const store=fixture(t,async()=>++calls===1?new Promise(resolve=>release=()=>resolve(json(revised(),201))):json(revised(),200));const pending=store.reviseBrief();store.suspend();assert.equal(store.getSnapshot().input,null);assert.equal(store.getSnapshot().base,null);assert.equal(await store.resolveRevision(),false);release();assert.equal(await pending,false);store.bindSession(session());assert.equal(store.getSnapshot().status,'unknown');assert.deepEqual(store.getSnapshot().input,patch);assert.equal(await store.replayRevision(patch),true);assert.equal(calls,2);});

test('actual SessionStore failed/malformed/network passiveGET stays paused until same identity verifies',async t=>{for(const respond of [()=>json(error(),503),()=>json({},200),()=>{throw Error('private');}]){let phase=0;const account=createSessionStore(createApiClient(async()=>++phase===1||phase===3?json(session()):respond()));t.after(()=>account.dispose());await account.refresh();const resources=createBriefRevisionResources(account,()=>createBriefRevisionStore(createApiClient(async()=>json(error(),503)),undefined,account.invalidateSession,()=>key));t.after(()=>resources.dispose());const store=resources.acquire('/same',project,research);store.observeLatest(base());store.setInput(patch);await store.reviseBrief();await account.refresh();assert.equal(store.getSnapshot().input,null);assert.equal(await store.replayRevision(patch),false);await account.refresh();assert.equal(resources.acquire('/same',project,research),store);store.observeLatest(base());assert.deepEqual(store.getSnapshot().input,patch);assert.equal(store.getSnapshot().status,'unknown');}});

test('canonical stale401 CAS happens before stale drop and protects changed owner/token',async t=>{for(const changedIdentity of [false,true]){let accountCalls=0,release;const account=createSessionStore(createApiClient(async()=>json(changedIdentity&&++accountCalls>1?session(other,'b'.repeat(64)):session())));t.after(()=>account.dispose());await account.refresh();const invalidations=[];const store=fixture(t,async()=>new Promise(resolve=>release=()=>resolve(json(error(),401))),undefined,(token,id)=>{const changed=account.invalidateSession(token,id);invalidations.push([token,id,changed]);return changed;});const pending=store.reviseBrief();if(changedIdentity){account.invalidate();await account.refresh();store.bindSession(account.getSnapshot().session);}else store.bindSession(null);release();assert.equal(await pending,false);assert.deepEqual(invalidations,[[csrf,owner,!changedIdentity]]);assert.equal(account.getSnapshot().status,changedIdentity?'authenticated':'anonymous');}});

test('late401 purges suspended local operation after failed passiveGET drops CAS',async t=>{let count=0,release;const account=createSessionStore(createApiClient(async()=>++count===1?json(session()):json(error(),503)));t.after(()=>account.dispose());await account.refresh();const resources=createBriefRevisionResources(account,()=>createBriefRevisionStore(createApiClient(async()=>new Promise(resolve=>release=()=>resolve(json(error(),401)))),undefined,account.invalidateSession,()=>key));t.after(()=>resources.dispose());const store=resources.acquire('/same',project,research);store.observeLatest(base());store.setInput(patch);const pending=store.reviseBrief();await account.refresh();release();assert.equal(await pending,false);store.bindSession(session());store.select(project,research);store.observeLatest(base());assert.equal(store.getSnapshot().input.target_user,undefined);});

test('malformed401/403/404/transport preserve global auth and redact raw error text',async t=>{for(const [respond,status]of [[()=>json({},401),'contract'],[()=>json(error(),403),'permission'],[()=>json(error(),404),'not_found'],[()=>{throw Error('private');},'unknown']]){let invalidated=0;const store=fixture(t,respond,undefined,()=>{invalidated++;return true;});await store.reviseBrief();assert.equal(store.getSnapshot().status,status);assert.equal(invalidated,0);assert.equal(store.matchesSession(session()),true);assert.ok(!store.getSnapshot().message.includes('Private'));}});

test('expiry purges capture and route/project/research holders dispose correctly',async t=>{let clock=Date.now();const store=fixture(t,async()=>json(error(),503),()=>clock);store.bindSession(session(owner,csrf,clock+10));await store.reviseBrief();clock+=11;assert.equal(await store.resolveRevision(),false);assert.equal(store.getSnapshot().input,null);const account=createSessionStore(createApiClient(async()=>json(session())));t.after(()=>account.dispose());await account.refresh();const resources=createBriefRevisionResources(account);t.after(()=>resources.dispose());const a=resources.acquire('/a',project,research);a.observeLatest(base());a.setInput(patch);resources.selectRoute('/b');assert.equal(a.getSnapshot().input,null);const b=resources.acquire('/b',project,research);assert.notEqual(a,b);assert.notEqual(resources.acquire('/b',project,other),b);});

test('cooldown blocks explicit recovery without automatic polling',async t=>{let clock=Date.now(),calls=0;const store=fixture(t,async()=>{calls++;return json(error(1),503);},()=>clock);await store.reviseBrief();assert.equal(await store.resolveRevision(),false);assert.equal(await store.replayRevision(patch),false);assert.equal(calls,1);clock+=1001;await store.resolveRevision();assert.equal(calls,2);});

test('retry notification research switch cannot carry old cooldown into the new scope',async t=>{const store=fixture(t,async()=>json(error(1),503));const unsubscribe=store.subscribe(()=>{if(store.getSnapshot().retryAfterSeconds!==null)store.select(project,other);});t.after(unsubscribe);await store.reviseBrief();store.observeLatest(base({research_id:other}));assert.equal(store.getSnapshot().researchId,other);assert.equal(store.getSnapshot().retryAfterSeconds,null);assert.equal(store.setInput(patch),true);});

test('real elapsed RetryAfter survives repeated verified passive refresh without extending its deadline or changing recovery',async t=>{
 const account=createSessionStore(createApiClient(async()=>json(session())));t.after(()=>account.dispose());await account.refresh();
 const calls=[];let keys=0;const input={...patch,business_model:null,constraints:{budget:null}};
 const resources=createBriefRevisionResources(account,()=>createBriefRevisionStore(createApiClient(async(path,init)=>{
  calls.push([path,init]);return calls.length===1?json(error(1),503):calls.length===2?json(error(),404):json(revised(input),200);
 }),undefined,account.invalidateSession,()=>{keys++;return key;}));t.after(()=>resources.dispose());
 const store=resources.acquire('/same',project,research);store.observeLatest(base());store.setInput(input);await store.reviseBrief();
 const started=performance.now(),until=async elapsed=>new Promise(resolve=>setTimeout(resolve,Math.max(0,elapsed-(performance.now()-started))));
 assert.equal(store.getSnapshot().retryAfterSeconds,1);
 for(const elapsed of [300,650]){
  await until(elapsed);const refresh=account.refresh();assert.equal(store.getSnapshot().input,null);assert.equal(await store.resolveRevision(),false);
  await refresh;assert.equal(resources.acquire('/same',project,research),store);store.observeLatest(base());
  assert.deepEqual(store.getSnapshot().input,input);assert.equal(store.getSnapshot().retryAfterSeconds,1);
  assert.equal(await store.replayRevision(input),false);
 }
 await until(1300);assert.equal(store.getSnapshot().retryAfterSeconds,null,'resume uses the first absolute deadline, rather than restarting the wait');
 assert.equal(store.getSnapshot().status,'unknown');assert.deepEqual(store.getSnapshot().input,input);assert.equal(calls.length,1,'elapsed time sends no receipt GET or POST');assert.equal(keys,1);
 assert.equal(await store.resolveRevision(),false);assert.equal(store.getSnapshot().status,'unknown');assert.equal(calls.length,2);
 assert.equal(await store.replayRevision(input),true);assert.equal(calls.length,3);assert.equal(keys,1);
 assert.equal(calls[1][0],`/api/backend/api/v1/projects/${project}/preparation-mutations/revise_brief/${key}`);
 assert.equal(calls[0][1].body,calls[2][1].body);assert.equal(calls[0][1].headers['Idempotency-Key'],calls[2][1].headers['Idempotency-Key']);assert.equal(calls[0][1].headers['X-CSRF-Token'],calls[2][1].headers['X-CSRF-Token']);
});

test('real elapsed RetryAfter expires while suspended and matching bind enables only manual original recovery immediately',async t=>{
 const calls=[];const store=fixture(t,async(path,init)=>{calls.push([path,init]);return calls.length===1?json(error(1),503):json(revised(),200);});
 await store.reviseBrief();store.suspend();await new Promise(resolve=>setTimeout(resolve,1300));
 assert.equal(store.getSnapshot().input,null);assert.equal(store.getSnapshot().retryAfterSeconds,null);assert.equal(await store.replayRevision(patch),false);assert.equal(calls.length,1);
 store.bindSession(session());store.observeLatest(base());assert.equal(store.getSnapshot().retryAfterSeconds,null);assert.deepEqual(store.getSnapshot().input,patch);assert.equal(calls.length,1);
 assert.equal(await store.replayRevision(patch),true);assert.equal(calls.length,2);assert.equal(calls[0][1].body,calls[1][1].body);assert.equal(calls[0][1].headers['Idempotency-Key'],calls[1][1].headers['Idempotency-Key']);
});
