// Generated by apps/api/scripts/generate_contracts.py. Do not edit.
export const schemaVersion = "1.0.0" as const;

export type AccessMethod = "api" | "permitted_http" | "manual_export" | "archive";

export type AddOnPackage = "saglik" | "fintech" | "egitim" | "gayrimenkul" | "seyahat" | "yeme-icme" | "regule-sektor" | "turkiye-pazari";

export type ApiError = { "schema_version": "1.0.0"; "code": string; "message": string; "request_id": string; "operation": (string | null); "stage": (Phase | null); "query_id": (string | null); "details_ref": (string | null); "source_id": (string | null); "retryable": boolean; "retry_after_seconds": (number | null); "usage": (Usage | null); "remaining_work": Array<string>; "next_step": (string | null); };

export type BriefContent = { "original_idea": string; "normalized_idea": (string | null); "product_type": ProvenanceField; "target_user": ProvenanceField; "problem_or_job": ProvenanceField; "context_or_niche": ProvenanceField; "market_scope": ProvenanceField; "business_model": ProvenanceField; "alternatives": ProvenanceField; "constraints": { [key: string]: ProvenanceField; }; "clarity_status": ClarityStatus; "missing_fields": Array<string>; "clarifying_questions": Array<string>; "assumption_ids": Array<string>; "skipped_clarification": boolean; "continue_with_unknowns": boolean; "language_scope": Array<string>; "primary_category": (ResearchCategory | null); "category_origin": (FieldOrigin | null); "category_confirmed": boolean; "add_on_packages": Array<AddOnPackage>; "secondary_categories": Array<ResearchCategory>; "modifiers": Array<string>; "category_rationale": (string | null); "known_unknowns": Array<string>; };

export type BudgetLimits = { "max_requests": number; "max_bytes": number; "max_pages": number; "max_records": number; "max_duration_seconds": number; "max_tokens": number; "max_cost_usd": string; "soft_cost_usd": string; "max_concurrency": number; };

export type Citation = { "schema_version": "1.0.0"; "user_id": string; "project_id": string; "research_id": string; "created_at": string; "versions": Versions; "citation_id": string; "claim_ids": Array<string>; "artifact_id": string; "document_id": string; "document_version": number; "segment_id": string; "source_id": string; "verbatim_quote": string; "start_offset": number; "end_offset": number; "segment_text_hash": string; "normalized_content_hash": string; "normalization_version": string; "source_url": string; "collected_at": string; "published_at": (string | null); "validation_status": ValidationStatus; "validated_at": (string | null); "rejection_reason": (string | null); };

export type Claim = { "schema_version": "1.0.0"; "user_id": string; "project_id": string; "research_id": string; "created_at": string; "versions": Versions; "claim_id": string; "claim_version": number; "claim_type": "problem_report" | "workaround" | "feature_request" | "competitor_complaint" | "competitor_praise" | "pricing_signal" | "stated_wtp_weak_signal" | "observed_payment_behavior" | "switching_signal" | "market_signal" | "counter_evidence"; "subject_entity": (string | null); "intent_ids": Array<string>; "independence_group_ids": Array<string>; "thesis": string; "statement": string; "direction": Direction; "evidence_type": EvidenceType; "citation_ids": Array<string>; "validation_status": ValidationStatus; "relevant": boolean; "market_match": (boolean | null); "independent_identity_key": (string | null); "ownership_key": (string | null); "limitations": Array<string>; };

export type ClarityStatus = "ready" | "needs_clarification" | "broad_but_continue";

export type ContentKind = "discovery" | "fetched_content";

export type CoverageAssessment = { "intent": SearchIntent; "status": "covered" | "partial" | "missing"; "independent_groups": number; "independent_source_families": number; "supporting_claims": number; "opposing_claims": number; "languages": Array<string>; "markets": Array<string>; "earliest_published_at": (string | null); "latest_published_at": (string | null); "rule_version": string; "limitations": Array<string>; };

export type DecisionReport = { "schema_version": "1.0.0"; "user_id": string; "project_id": string; "research_id": string; "created_at": string; "versions": Versions; "report_id": string; "report_version": number; "previous_report_id": (string | null); "bundle_id": string; "bundle_version": number; "outcome": Outcome; "status": "published"; "management_review_required": true; "market_assessment": Array<ReportStatement>; "summary": Array<ReportStatement>; "rationale": Array<RationaleBlock>; "counter_evidence": Array<ReportStatement>; "known_unknowns": Array<string>; "limitations": Array<string>; "sufficiency": SufficiencyAssessment; "gap_ids": Array<string>; "pillar_profiles": Array<PillarProfile>; "target_customer": Array<ReportStatement>; "problem": Array<ReportStatement>; "competitors": Array<ReportStatement>; "opportunity_hypotheses": Array<ReportStatement>; "supporting_claim_ids": Array<string>; "opposing_claim_ids": Array<string>; "citation_ids": Array<string>; "critical_unknowns": Array<string>; "assumptions": Array<string>; "execution_constraints": Array<string>; "user_conditions_snapshot": { [key: string]: ProvenanceField; }; "primary_validation": PrimaryValidation; "decision_stability": DecisionStability; "next_actions": Array<NextAction>; "modification": (Modification | null); "investigation": (Investigation | null); "usage": Usage; "validation": ReportValidation; "errors": Array<ApiError>; };

export type DecisionStability = { "status": "stable" | "sensitive" | "fragile" | "not_evaluated"; "method": (string | null); "critical_claim_ids": Array<string>; "assumptions_that_change_outcome": Array<string>; };

export type Direction = "supports" | "opposes" | "context" | "unknown";

export type DocumentRelation = { "relation_id": string; "from_id": string; "to_id": string; "relation_type": "duplicate_of" | "repost_of" | "comment_on" | "quote_of" | "derived_from" | "same_entity_candidate"; "method": string; "review_status": "confirmed" | "candidate" | "rejected"; };

export type EvidenceBundle = { "schema_version": "1.0.0"; "user_id": string; "project_id": string; "research_id": string; "created_at": string; "versions": Versions; "bundle_id": string; "bundle_version": number; "status": "complete" | "partial" | "insufficient"; "source_reports": Array<SourceReport>; "claims": Array<Claim>; "citations": Array<Citation>; "coverage": Partial<Record<SearchIntent, Array<string>>>; "coverage_assessments": Array<CoverageAssessment>; "independence": Array<IndependenceGroup>; "relations": Array<DocumentRelation>; "evidence_maps": EvidenceMaps; "selection_trace_ref": (string | null); "source_registry_version": string; "parent_bundle_id": (string | null); "gap_ids": Array<string>; "duplicate_document_ids": Array<string>; "known_unknowns": Array<string>; "limitations": Array<string>; "usage": Usage; };

export type EvidenceMapEntry = { "name": string; "assessment": (string | null); "status": "evidenced" | "unknown"; "evidence_type": (EvidenceType | null); "claim_ids": Array<string>; "limitations": Array<string>; };

export type EvidenceMaps = { "problems": Array<EvidenceMapEntry>; "voice_of_customer": Array<EvidenceMapEntry>; "competitors": Array<EvidenceMapEntry>; "pricing": Array<EvidenceMapEntry>; "opportunity_hypotheses": Array<EvidenceMapEntry>; "market_maturity": "existing" | "resegmented" | "emerging" | "new" | "unknown"; "market_maturity_claim_ids": Array<string>; "market_maturity_limitations": Array<string>; };

export type EvidenceType = "direct_experience" | "official_claim" | "observed_pricing" | "willingness_to_pay" | "observed_payment" | "observed_usage" | "other";

export type ExtractionField = { "name": string; "value_type": "text" | "integer" | "number" | "date" | "url" | "boolean"; "required": boolean; "locator": string; };

export type FieldOrigin = "user_stated" | "user_confirmed" | "ai_inferred" | "ai_hypothesis";

export type FieldState = "known" | "inferred" | "missing" | "conflicting";

export type GapKind = "investigate_secondary" | "validate_primary";

export type IdeaBrief = { "schema_version": "1.0.0"; "user_id": string; "project_id": string; "research_id": string; "created_at": string; "versions": Versions; "brief_id": string; "brief_version": number; "status": "draft" | "awaiting_user" | "confirmed"; "content": BriefContent; };

export type IndependenceGroup = { "group_id": string; "claim_ids": Array<string>; "document_ids": Array<string>; "status": "known" | "unknown"; "reason": string; "identity_key": (string | null); "ownership_key": (string | null); };

export type Investigation = { "subtype": "investigate_secondary" | "validate_primary" | "mixed"; "gap_ids": Array<string>; "priority_reason": string; };

export type Modification = { "preserve_signal": string; "change_assumption": string; "proposed_focus": string; "avoid": Array<string>; "evidence_to_reassess": Array<string>; "basis_claim_ids": Array<string>; "assumptions": Array<string>; };

export type NextAction = { "action_id": string; "kind": "secondary_research" | "report_primary_gap" | "management_review" | "reassess"; "target_segment": (string | null); "question_or_hypothesis": string; "evidence_to_capture": Array<string>; "priority_reason": string; "reassessment_trigger": string; };

export type NormalizedDocument = { "schema_version": "1.0.0"; "user_id": string; "project_id": string; "research_id": string; "created_at": string; "versions": Versions; "document_id": string; "artifact_id": string; "external_id": (string | null); "document_type": "article" | "review" | "comment" | "api_record" | "official_page" | "other"; "title": (string | null); "body_original_ref": string; "canonical_url": (string | null); "parent_document_id": (string | null); "author_reference": (string | null); "collected_at": string; "updated_at": (string | null); "locale": (string | null); "engagement_metadata": { [key: string]: (number | string | null); }; "supersedes_document_id": (string | null); "document_version": number; "status": "normalized" | "rejected"; "normalized_text": string; "normalized_content_hash": string; "normalization_version": string; "language": (string | null); "published_at": (string | null); "source_url": string; "segments": Array<TextSegment>; "exact_duplicate_of": (string | null); "near_duplicate_of": (string | null); "independent_identity_key": (string | null); "ownership_key": (string | null); "quality_flags": Array<string>; };

export type Outcome = "positive_findings" | "modify" | "kill" | "investigate_more";

export type PageInfo = { "next_cursor": (string | null); "limit": number; };

export type PermissionStatus = "permitted" | "blocked" | "requires_authorization" | "unknown";

export type Phase = "planning" | "evidence" | "decision";

export type PillarProfile = { "pillar": "problem" | "customer" | "competition" | "opportunity" | "feasibility" | "evidence_quality"; "status": "strong" | "mixed" | "weak" | "insufficient"; "supporting_claim_ids": Array<string>; "opposing_claim_ids": Array<string>; "known_unknowns": Array<string>; };

export type PrimaryValidation = { "status": "not_started" | "partial" | "available"; "observation_refs": Array<string>; "observation_count": number; "unvalidated_behaviors": Array<string>; };

export type Project = { "schema_version": "1.0.0"; "project_id": string; "user_id": string; "name": string; "created_at": string; "archived_at": (string | null); };

export type ProjectPage = { "schema_version": "1.0.0"; "items": Array<Project>; "page": PageInfo; };

export type ProvenanceField = { "value": (string | null); "state": FieldState; "origin": (FieldOrigin | null); "assumption_id": (string | null); "conflicting_values": Array<string>; "prior_origins": Array<FieldOrigin>; "confirmed": boolean; };

export type QueryExecution = { "schema_version": "1.0.0"; "user_id": string; "project_id": string; "research_id": string; "created_at": string; "versions": Versions; "execution_id": string; "query_id": string; "source_id": string; "attempt": number; "status": SourceStatus; "counts": SourceCounts; "usage": Usage; "error": (ApiError | null); "started_at": (string | null); "finished_at": (string | null); };

export type QueryPlanItem = { "query_id": string; "intent_id": string; "question": string; "intent": SearchIntent; "source_id": string; "query_text": string; "language": string; "market_scope": (string | null); "origin": FieldOrigin; "user_confirmed": boolean; "query_kind": "local_index" | "fulltext" | "site_search" | "opensearch" | "api"; "surface_id": string; "priority": number; "expected_fields": Array<string>; "origin_refs": Array<string>; "limits": SourceLimits; };

export type RationaleBlock = { "block_id": string; "statement": string; "kind": "evidence_interpretation" | "assumption" | "recommendation" | "limitation"; "claim_ids": Array<string>; "citation_ids": Array<string>; };

export type RawArtifact = { "schema_version": "1.0.0"; "user_id": string; "project_id": string; "research_id": string; "created_at": string; "versions": Versions; "artifact_id": string; "execution_id": string; "query_id": string; "source_id": string; "source_url": string; "fetched_url": (string | null); "collected_at": string; "published_at": (string | null); "archive_captured_at": (string | null); "license_or_restriction": (string | null); "research_plan_version": number; "access_method": AccessMethod; "artifact_origin": "live_capture" | "archive_copy"; "content_kind": ContentKind; "status": SourceStatus; "body_ref": (string | null); "content_hash": (string | null); "byte_count": number; "media_type": (string | null); "connector_version": string; "fields": { [key: string]: (string | null); }; "error": (ApiError | null); };

export type ReportStatement = { "text": string; "claim_ids": Array<string>; "citation_ids": Array<string>; };

export type ReportValidation = { "schema_check": "passed"; "identity": "passed"; "source_binding": "passed"; "outcome_policy": "passed"; "scope": "passed"; "validator_version": string; };

export type ResearchCategory = "mobil-uygulama" | "b2b-web-yazilimi" | "gelistirici-araci" | "eklenti-entegrasyon" | "yapay-zeka-urunu" | "oyun" | "yerel-hizmet";

export type ResearchGapRequest = { "schema_version": "1.0.0"; "user_id": string; "project_id": string; "research_id": string; "created_at": string; "versions": Versions; "gap_id": string; "gap_version": number; "parent_bundle_id": string; "parent_bundle_version": number; "parent_report_id": (string | null); "parent_report_version": (number | null); "intent_id": (string | null); "severity": "critical" | "high" | "medium" | "low"; "eligible_source_ids": Array<string>; "expected_evidence_type": (EvidenceType | null); "kind": GapKind; "question": string; "missing_evidence": Array<string>; "proposed_queries": Array<QueryPlanItem>; "remaining_budget": (BudgetLimits | null); "cycle": number; "max_cycles": number; "stop_conditions": Array<string>; "status": "proposed" | "approved" | "running" | "closed" | "stopped"; };

export type ResearchIntent = { "intent_id": string; "intent": SearchIntent; "question": string; "priority": number; "brief_basis": Array<string>; "expected_fields": Array<string>; "required_evidence_types": Array<EvidenceType>; "validation_kind": GapKind; "included": boolean; "exclusion_reason": (string | null); };

export type ResearchMode = "standard" | "deep_research";

export type ResearchPlan = { "schema_version": "1.0.0"; "user_id": string; "project_id": string; "research_id": string; "created_at": string; "versions": Versions; "research_plan_id": string; "plan_version": number; "plan_fingerprint": string; "status": "draft" | "awaiting_user" | "confirmed"; "brief_id": string; "brief_version": number; "brief": BriefContent; "research_mode": ResearchMode; "intents": Array<ResearchIntent>; "source_plan": Array<SourcePlanItem>; "query_plan": Array<QueryPlanItem>; "budget": BudgetLimits; "known_unknowns": Array<string>; "confirmed_at": (string | null); };

export type ResearchRun = { "schema_version": "1.0.0"; "user_id": string; "project_id": string; "research_id": string; "created_at": string; "versions": Versions; "status": RunStatus; "phase": Phase; "brief_id": string; "brief_version": number; "research_plan_id": string; "plan_version": number; "plan_fingerprint": string; "budget": BudgetLimits; "usage": Usage; "cancel_requested": boolean; "source_executions": Array<QueryExecution>; "bundle_id": (string | null); "report_id": (string | null); "errors": Array<ApiError>; "started_at": (string | null); "finished_at": (string | null); };

export type RunPage = { "schema_version": "1.0.0"; "items": Array<ResearchRun>; "page": PageInfo; };

export type RunStatus = "draft" | "awaiting_user" | "planned" | "queued" | "acquiring" | "normalizing" | "analyzing" | "deciding" | "completed" | "partial" | "cancelled" | "failed";

export type SearchIntent = "problem_demand" | "existing_alternatives" | "dissatisfaction" | "observed_market_pricing" | "use_case" | "competitor_discovery" | "counter_evidence" | "stated_wtp_weak_signal" | "technical_feasibility" | "regulatory_constraints" | "adoption_signals";

export type Session = { "schema_version": "1.0.0"; "user": User; "expires_at": string; };

export type SourceCounts = { "discovered": number; "fetched": number; "normalized": number; "eligible": number; "unique": number; "independent": number; "claims": number; };

export type SourceFamily = "official_web" | "technical_community" | "marketplace_review" | "social_community" | "domain_web" | "ads_trends_business" | "public_academic_regulation" | "vertical";

export type SourceHealth = "supported" | "qualified" | "unavailable" | "blocked" | "deferred";

export type SourceLimits = { "max_items": number; "max_pages": number; "max_requests": number; "max_response_bytes": number; "max_total_bytes": number; "max_seconds": number; "max_retries": number; "max_llm_tokens": number; };

export type SourcePlanItem = { "source_id": string; "profile_version": string; "connector_id": string; "connector_version": string; "family": SourceFamily; "permission": PermissionStatus; "health": SourceHealth; "access_method": AccessMethod; "allowed_origins": Array<string>; "surface_id": string; "capabilities": Array<"search" | "fetch" | "metadata" | "reviews" | "archive">; "allowed_content_types": Array<string>; "eligible_categories": Array<ResearchCategory>; "supported_intents": Array<SearchIntent>; "extract_fields": Array<ExtractionField>; "access_policy_version": string; "retention_policy_version": string; "rate_limit_policy_version": string; "access_reviewed_at": string; "fallback_source_ids": Array<string>; "limits": SourceLimits; "expected_fields": Array<string>; "language_scope": Array<string>; "market_scope": (string | null); "ownership_key": (string | null); "limitations": Array<string>; };

export type SourceReport = { "schema_version": "1.0.0"; "user_id": string; "project_id": string; "research_id": string; "created_at": string; "versions": Versions; "source_report_id": string; "source_id": string; "query_ids": Array<string>; "coverage": { [key: string]: Array<string>; }; "stop_reason": "completed" | "coverage_reached" | "no_new_evidence" | "exhausted_results" | "budget_exhausted" | "time_exhausted" | "no_eligible_sources" | "cancelled" | "error"; "status": SourceStatus; "counts": SourceCounts; "claim_ids": Array<string>; "citation_ids": Array<string>; "supporting_claim_ids": Array<string>; "opposing_claim_ids": Array<string>; "known_unknowns": Array<string>; "limitations": Array<string>; "usage": Usage; "errors": Array<ApiError>; };

export type SourceStatus = "queued" | "running" | "succeeded" | "no_results" | "source_unavailable" | "rate_limited" | "blocked_by_policy" | "challenge" | "invalid_output" | "partial" | "cancelled" | "failed";

export type SufficiencyAssessment = { "status": "sufficient" | "insufficient"; "thesis": string; "direction": Direction; "independent_examples": number; "independent_sources": number; "minimum_examples": 3; "minimum_sources": 2; "qualitative_checks": { [key: string]: "passed" | "failed" | "unknown"; }; "blocking_reasons": Array<string>; "eligible_outcomes": Array<Outcome>; "policy_version": string; };

export type TextSegment = { "schema_version": "1.0.0"; "user_id": string; "project_id": string; "research_id": string; "created_at": string; "versions": Versions; "segment_id": string; "document_id": string; "segment_type": "body" | "title" | "review" | "comment" | "quote" | "other"; "text": string; "start_offset": number; "end_offset": number; "text_hash": string; "normalized_content_hash": string; "source_locator": (string | null); "normalization_version": string; };

export type Usage = { "requests": number; "bytes": number; "pages": number; "records": number; "duration_seconds": number; "input_tokens": number; "output_tokens": number; "cost_usd": string; "reserved_cost_usd": string; "provider_result_unknown": boolean; };

export type User = { "schema_version": "1.0.0"; "user_id": string; "email": string; "created_at": string; };

export type ValidationStatus = "pending" | "validated" | "rejected";

export type Versions = { "brief": (number | null); "plan": (number | null); "evidence_bundle": (number | null); "category_catalog": (string | null); "source_registry": (string | null); "connectors": { [key: string]: string; }; "prompts": { [key: string]: string; }; "model": (string | null); "normalizer": (string | null); "extractor": (string | null); "decision_policy": (string | null); "validator": (string | null); };
