"use client";
import { useEffect, useRef, useState } from "react";
import type { ReactNode } from "react";
import type { WireModels } from "@/lib/api/wire";
import { authorizedBudget, useResearchWorkspace } from "@/lib/research/workspace";
import type { Read } from "@/lib/research/workspace";
import { ProjectAccess } from "@/components/projects/project-access";

export const researchButton = "min-h-11 rounded-lg border border-[var(--line)] bg-white px-4 py-2 text-sm font-semibold text-[var(--brand-deep)] disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--brand)]";
const input = "mt-1 min-h-11 w-full rounded-lg border border-[var(--line)] bg-white px-3 py-2 text-sm text-[var(--ink)] focus-visible:outline-2 focus-visible:outline-[var(--brand)]";
const outcomeLabels: Record<string, string> = { positive_findings: "Olumlu bulgular — yönetici değerlendirmesi bekliyor", modify: "Modify — araştırma odağı değişikliği", kill: "Kill — mevcut tez karşıt kanıtla desteklenmiyor", investigate_more: "Investigate More — eksik kanıt" };
export type ResearchView = "all" | "run" | "evidence" | "report" | "competitors" | "problems";
function Card({ title, children }: { title: string; children: ReactNode }) { return <section className="min-w-0 space-y-4 rounded-xl border border-[var(--line)] bg-white p-5 sm:p-6"><h2 className="text-lg font-semibold text-[var(--ink)]">{title}</h2>{children}</section>; }
function Texts({ items }: { items: string[] }) { return items.length ? <ul className="list-disc space-y-1 pl-5 text-sm leading-6">{items.map((value, index) => <li className="whitespace-pre-wrap break-words" key={index}>{value}</li>)}</ul> : <p className="text-sm text-[#686973]">Kayıt yok.</p>; }
function Notice({ read, empty }: { read: { status: string; message: string | null }; empty: string }) { return read.status === "ready" ? null : <p role={read.status === "error" ? "alert" : "status"} className="text-sm leading-6 text-[#686973]">{read.status === "loading" || read.status === "idle" ? "Backend kaydı okunuyor…" : read.status === "missing" ? empty : read.message}</p>; }
function Usage({ usage }: { usage: WireModels["Usage"] }) { return <div className="grid gap-2 text-sm sm:grid-cols-3"><p>{usage.requests} dış istek · {usage.bytes} byte</p><p>{usage.pages} sayfa · {usage.records} kayıt</p><p>{usage.input_tokens + usage.output_tokens} token · ${usage.cost_usd}</p><p>{Math.round(usage.duration_seconds)} saniye · rezerve ${usage.reserved_cost_usd}</p>{usage.provider_result_unknown ? <p className="sm:col-span-2" role="status">Provider sonucu belirsiz; uzlaştırılmadan yeni harcama yapılamaz.</p> : null}</div>; }
export function BudgetFields({ value, change, disabled = false }: { value: WireModels["BudgetLimits"]; change: (value: WireModels["BudgetLimits"]) => void; disabled?: boolean }) {
  return <fieldset disabled={disabled} className="grid gap-3 sm:grid-cols-3"><legend className="mb-2 text-sm font-semibold">Sert araştırma sınırları</legend>{Object.entries(value).map(([name, amount]) => <label className="min-w-0 text-xs" key={name}>{name.replaceAll("_", " ")}<input className={input} type="number" min={name === "max_concurrency" ? 1 : 0} max={Number(authorizedBudget[name as keyof typeof authorizedBudget])} step={typeof amount === "string" ? "0.000001" : 1} value={amount} onChange={event => { const next = event.target.value; if (typeof amount === "string") change({ ...value, [name]: next }); else if (Number.isSafeInteger(Number(next))) change({ ...value, [name]: Number(next) }); }} /></label>)}</fieldset>;
}

export function ResearchWorkspace({ projectId, researchId, view = "all" }: { projectId: string; researchId: string; view?: ResearchView }) {
  const workspace = useResearchWorkspace(projectId, researchId);
  const { base, account } = workspace;
  const brief = workspace.brief.data;
  const planRecord = workspace.plan.data, plan = planRecord?.plan;
  const [budget, setBudget] = useState(authorizedBudget);
  const [mode, setMode] = useState<"standard" | "deep_research">("standard");
  const [accepted, setAccepted] = useState<string[]>([]), [category, setCategory] = useState("current"), [continueUnknown, setContinueUnknown] = useState(false);
  const [confirmedQueries, setConfirmedQueries] = useState<string[]>([]), [acknowledged, setAcknowledged] = useState<string[]>([]);
  const [excludedSources, setExcludedSources] = useState<string[]>([]), [excludedQueries, setExcludedQueries] = useState<string[]>([]);
  const [queryEdits, setQueryEdits] = useState<Record<string, string>>({});
  const [intentEdits, setIntentEdits] = useState<Record<string, { included: boolean; reason: string | null }>>({});
  const [reportPage, setReportPage] = useState<Read<"DecisionReportPage">>({ data: null, status: "idle", message: null });
  const [planPage, setPlanPage] = useState<Read<"ResearchPlanPage">>({ data: null, status: "idle", message: null });
  const [selectedReport, setSelectedReport] = useState<Read<"DecisionReport"> | null>(null);
  const [selectedPlan, setSelectedPlan] = useState<Read<"ResearchPlanPreparation"> | null>(null);
  const [citation, setCitation] = useState<WireModels["Citation"] | null>(null), [document, setDocument] = useState<WireModels["NormalizedDocument"] | null>(null);
  const [detailMessage, setDetailMessage] = useState<string | null>(null), [filter, setFilter] = useState("all");
  const analysis = workspace.analyses.data?.items.filter(item => item.analysis_kind === "brief" && brief && item.input_brief_id === brief.brief_id && item.input_brief_version === brief.brief_version).at(-1);
  const planAnalysis = workspace.analyses.data?.items.filter(item => item.analysis_kind === "plan" && brief && item.input_brief_id === brief.brief_id && item.input_brief_version === brief.brief_version).at(-1);
  const locked = workspace.busy || workspace.pending !== null;
  useEffect(() => { setAccepted([]); setCategory("current"); setContinueUnknown(false); }, [brief?.brief_id, brief?.brief_version, analysis?.analysis_id]);
  useEffect(() => { setConfirmedQueries([]); setAcknowledged([]); setExcludedSources([]); setExcludedQueries([]); setQueryEdits({}); setIntentEdits({}); if (plan) { setBudget(plan.budget); setMode(plan.research_mode); } }, [plan?.research_plan_id, plan?.plan_version]);
  useEffect(() => { if (!account.session || plan) return; void workspace.request("UserSettings", "/api/v1/settings").then(result => { if (result?.ok) { setBudget(result.data.default_budget); setMode(result.data.default_research_mode); } }); }, [account.session?.user.user_id, plan, workspace.request]);
  const toggle = (values: string[], value: string, enabled: boolean) => enabled ? [...new Set([...values, value])] : values.filter(item => item !== value);
  const expectedBrief = brief ? { expected_brief_id: brief.brief_id, expected_brief_version: brief.brief_version } : null;
  const selection = plan ? { expected_plan_id: plan.research_plan_id, expected_plan_version: plan.plan_version, expected_plan_fingerprint: plan.plan_fingerprint, expected_brief_id: plan.brief_id, expected_brief_version: plan.brief_version } : null;
  function recovery(operation: string) { return `/api/v1/projects/${projectId}/plan-operations/${operation}/{key}`; }
  const citationSelection = useRef(0);
  async function readCitation(identity: string) {
    const selected = ++citationSelection.current;
    setCitation(null); setDocument(null); setDetailMessage("Alıntı bağlamı okunuyor…");
    const result = await workspace.request("Citation", `${base}/citations/${identity}`);
    if (selected !== citationSelection.current) return;
    if (!result?.ok) { setDetailMessage(result && !result.ok ? result.apiError?.message ?? result.message : "Oturum değişti."); return; }
    setCitation(result.data);
    const content = await workspace.request("NormalizedDocument", `${base}/documents/${result.data.document_id}/versions/${result.data.document_version}`);
    if (selected !== citationSelection.current) return;
    if (content?.ok) { setDocument(content.data); setDetailMessage(null); } else setDetailMessage(content && !content.ok ? content.apiError?.message ?? content.message : "Belge bağlamı okunamadı.");
  }
  function facts(items: WireModels["ReportStatement"][]) { return items.length ? <ul className="space-y-3">{items.map((item, index) => <li className="rounded-lg border border-[var(--line)] p-3 text-sm" key={index}><p className="whitespace-pre-wrap break-words leading-6">{item.text}</p><div className="mt-2 flex flex-wrap gap-2">{item.citation_ids.map((identity, quote) => <button type="button" className={researchButton} key={identity} onClick={() => void readCitation(identity)}>Alıntı {quote + 1}</button>)}</div></li>)}</ul> : <p className="text-sm text-[#686973]">Bu bölüm için doğrulanmış bulgu yok.</p>; }
  if (!account.session) return <ProjectAccess status={account.status} message={account.message} refresh={account.refresh} />;
  const visibleReport = selectedReport ? selectedReport.data : workspace.report.data;
  const evidence = workspace.bundle.data;
  const unicodeText = document ? Array.from(document.normalized_text) : null;
  return <div className="space-y-5 break-words" aria-busy={workspace.busy}>
    <div className="flex flex-wrap items-center gap-3"><button className={researchButton} disabled={workspace.busy} type="button" onClick={() => void workspace.refresh()}>Kayıtları yenile</button><p className="min-w-0 break-all text-xs text-[#686973]">Araştırma: {researchId}</p></div>
    {workspace.notice ? <p role="status" className="rounded-lg border border-[var(--line)] bg-white p-4 text-sm leading-6">{workspace.notice}</p> : null}
    {workspace.pending ? <Card title="İşlem sonucu belirsiz"><p className="text-sm leading-6">Aynı kaydı koruyan işlem anahtarı: <span className="break-all">{workspace.pending.key}</span>. Yeni bir araştırma veya yeni ücretli deneme oluşturulmaz.</p><div className="flex flex-wrap gap-3"><button className={researchButton} disabled={workspace.busy} onClick={() => void workspace.recover()} type="button">Kaydedilen işlemi kontrol et</button><button className={researchButton} disabled={workspace.busy} onClick={() => void workspace.retry()} type="button">Aynı anahtar ve girdiyi yeniden gönder</button></div></Card> : null}
    {view === "all" ? <>
      <Card title="Faz 1 · Netleştirme ve insan onayı"><Notice read={workspace.brief} empty="Bu araştırmanın brief kaydı yok." />{brief ? <>
        <p className="text-sm">Brief v{brief.brief_version} · {brief.status} · kategori: {brief.content.primary_category ?? "unmatched"}</p>
        <button className={researchButton} disabled={locked || brief.status === "confirmed"} type="button" onClick={() => void workspace.mutate("PreparationAnalysisOperation", `${base}/analyses`, { kind: "brief", ...expectedBrief, budget }, `/api/v1/projects/${projectId}/analysis-operations/analyze_brief/{key}`, "PreparationAnalysisOperation")}>AI netleştirme önerilerini getir</button>
        <Notice read={workspace.analyses} empty="Netleştirme önerisi kaydı yok." />
        {analysis ? <><p className="text-sm">AI önerileri kendiliğinden onaylanmaz. Original idea korunur.</p>{analysis.normalized_idea ? <p className="whitespace-pre-wrap text-sm leading-6">Önerilen anlatım: {analysis.normalized_idea}</p> : null}<Texts items={analysis.clarifying_questions} />{analysis.field_proposals.map(item => <label className="flex items-start gap-3 text-sm leading-6" key={item.proposal_id}><input className="mt-1 h-5 w-5 shrink-0" type="checkbox" checked={accepted.includes(item.proposal_id)} disabled={locked || brief.status === "confirmed"} onChange={event => setAccepted(toggle(accepted, item.proposal_id, event.target.checked))} /><span>{item.field_path}: {item.value ?? "unknown"} · {item.origin}<span className="block text-xs">Varsayım: {item.assumption_id} · dayanak: {item.basis_refs.join(", ")}</span></span></label>)}<Texts items={analysis.known_unknowns} /></> : null}
        <label className="block text-sm">Kategori seçimi<select className={input} value={category} disabled={locked || brief.status === "confirmed"} onChange={event => setCategory(event.target.value)}><option value="current">Mevcut insan seçimi</option>{analysis?.category_proposal ? <option value="proposal">AI önerisi: {analysis.category_proposal.primary_category}</option> : null}<option value="unmatched">Eşleşmiyor / unknown</option></select></label>
        {analysis?.category_proposal ? <p className="text-sm leading-6">Kategori gerekçesi: {analysis.category_proposal.rationale}</p> : null}
        <label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5" type="checkbox" checked={continueUnknown} disabled={locked || brief.status === "confirmed"} onChange={event => setContinueUnknown(event.target.checked)} />Netleştirmeyi atlayıp açık bilinmeyenlerle devam etmeyi kabul ediyorum.</label>
        <button className={researchButton} disabled={locked || brief.status === "confirmed"} onClick={() => void workspace.mutate("IdeaBrief", `${base}/confirm`, { ...expectedBrief, analysis_id: analysis?.analysis_id ?? null, accepted_proposal_ids: accepted, category_choice: category, category_proposal_id: category === "proposal" ? analysis?.category_proposal?.proposal_id : null, skipped_clarification: continueUnknown, continue_with_unknowns: continueUnknown }, `/api/v1/projects/${projectId}/preparation-mutations/confirm_brief/{key}`, "PreparationMutationReceipt")} type="button">Seçimlerimle brief’i onayla</button>
      </> : null}</Card>
      <Card title="Faz 1 · Sürümlü araştırma planı">
        <BudgetFields value={budget} change={setBudget} disabled={locked} /><label className="block text-sm">Araştırma modu<select className={input} value={mode} disabled={locked} onChange={event => setMode(event.target.value as typeof mode)}><option value="standard">Standard</option><option value="deep_research">Deep research</option></select></label>
        <p className="text-xs leading-5 text-[#686973]">Bunlar üst sınırlardır; önceki harcamalar ve suite’in kalan kapasitesi korunur. Deep research ek ücretli yetki vermez.</p>
        <button className={researchButton} disabled={locked || brief?.status !== "confirmed" || !!plan} type="button" onClick={() => void workspace.mutate("ResearchPlan", `${base}/plans`, { ...expectedBrief, analysis_id: planAnalysis?.analysis_id ?? null, research_mode: mode, budget }, recovery("draft_plan"), "PlanMutationReceipt")}>Onaylanan brief’ten plan oluştur</button>
        {!plan && brief?.status === "confirmed" ? <button className={researchButton} disabled={locked} type="button" onClick={() => void workspace.mutate("PreparationAnalysisOperation", `${base}/analyses`, { kind: "plan", ...expectedBrief, budget }, `/api/v1/projects/${projectId}/analysis-operations/propose_plan/{key}`, "PreparationAnalysisOperation")}>Plan öncesi AI niyet ve sorgu önerileri</button> : null}
        {planAnalysis ? <details><summary className="cursor-pointer text-sm font-semibold">Plan önerileri · insan incelemesi gerekir</summary><ul className="mt-3 space-y-2 text-sm">{planAnalysis.intent_proposals.map(item => <li key={item.proposal_id}>{item.intent}: {item.question} · AI önerisi</li>)}{planAnalysis.query_hypotheses.map(item => <li className="break-words" key={item.proposal_id}>{item.language}: {item.query_text} · {item.origin}</li>)}</ul></details> : null}
        <Notice read={workspace.plan} empty="Henüz araştırma planı oluşturulmadı." />
        {plan && planRecord ? <>
          <p className="break-all text-sm">Plan v{plan.plan_version} · {plan.status} · fingerprint {plan.plan_fingerprint}</p><Texts items={plan.known_unknowns} />
          <h3 className="font-semibold">Niyet ve kapsama boşlukları</h3><ul className="space-y-2 text-sm">{plan.intents.map(item => { const decision = intentEdits[item.intent_id] ?? { included: item.included, reason: item.exclusion_reason }; return <li className="space-y-2 rounded-lg border border-[var(--line)] p-3" key={item.intent_id}><label className="flex items-start gap-3"><input className="mt-1 h-5 w-5" type="checkbox" disabled={locked || !!workspace.run.data} checked={decision.included} onChange={event => setIntentEdits({ ...intentEdits, [item.intent_id]: { included: event.target.checked, reason: event.target.checked ? null : decision.reason ?? "" } })} /><span>{item.intent} · {item.question}</span></label>{!decision.included ? <label className="block">Hariç tutma gerekçesi<input className={input} disabled={locked || !!workspace.run.data} value={decision.reason ?? ""} onChange={event => setIntentEdits({ ...intentEdits, [item.intent_id]: { included: false, reason: event.target.value } })} /></label> : null}</li>; })}</ul>
          <p className="text-sm">Başlatma engelleri:</p><Texts items={planRecord.eligibility.blocking_reasons} />
          {plan.source_plan.map(item => <label className="flex items-start gap-3 rounded-lg border border-[var(--line)] p-3 text-sm" key={item.source_id}><input className="mt-1 h-5 w-5" type="checkbox" disabled={locked || !!workspace.run.data} checked={excludedSources.includes(item.source_id)} onChange={event => setExcludedSources(toggle(excludedSources, item.source_id, event.target.checked))} /><span>Kaynağı yeni sürümden çıkar: {item.source_id} · {item.family} · {item.access_method}<span className="block">{item.permission} · {item.health} · {item.surface_id} · en fazla {item.limits.max_items} kayıt</span><span className="block break-all text-xs">{item.allowed_origins.join(", ")}</span></span></label>)}
          {plan.query_plan.map(item => <fieldset className="space-y-2 rounded-lg border border-[var(--line)] p-3" disabled={locked || !!workspace.run.data} key={item.query_id}><legend className="px-1 text-sm font-semibold">{item.intent} · {item.source_id} · {item.language}</legend><p className="text-sm">{item.question}</p><label className="block text-sm">Sorgu metni<textarea className={input} maxLength={1000} value={queryEdits[item.query_id] ?? item.query_text} onChange={event => setQueryEdits({ ...queryEdits, [item.query_id]: event.target.value })} /></label><label className="flex items-center gap-3 text-sm"><input className="h-5 w-5" type="checkbox" checked={excludedQueries.includes(item.query_id)} onChange={event => setExcludedQueries(toggle(excludedQueries, item.query_id, event.target.checked))} />Yeni sürümden çıkar</label><label className="flex items-center gap-3 text-sm"><input className="h-5 w-5" type="checkbox" checked={confirmedQueries.includes(item.query_id)} onChange={event => setConfirmedQueries(toggle(confirmedQueries, item.query_id, event.target.checked))} />Bu kaydedilmiş sorguyu onaylıyorum</label></fieldset>)}
          {planRecord.eligibility.coverage_gaps.map(item => <label className="flex items-start gap-3 text-sm" key={item.gap_id}><input className="mt-1 h-5 w-5" type="checkbox" disabled={locked} checked={acknowledged.includes(item.gap_id)} onChange={event => setAcknowledged(toggle(acknowledged, item.gap_id, event.target.checked))} /><span>Kapsama boşluğunu kabul ediyorum: {item.reason}</span></label>)}
          <div className="flex flex-wrap gap-3"><button className={researchButton} disabled={locked || !!workspace.run.data} type="button" onClick={() => void workspace.mutate("ResearchPlan", `${base}/plans/revise`, { ...selection, research_mode: mode, budget, excluded_source_ids: excludedSources, excluded_query_ids: excludedQueries, intent_decisions: Object.entries(intentEdits).map(([intent_id, decision]) => ({ intent_id, ...decision })), query_edits: Object.entries(queryEdits).filter(([identity]) => !excludedQueries.includes(identity)).map(([query_id, query_text]) => ({ query_id, query_text })) }, recovery("revise_plan"), "PlanMutationReceipt")}>Değişikliklerle yeni plan sürümü kaydet</button>
            <button className={researchButton} disabled={locked || plan.status === "confirmed" || !planRecord.eligibility.can_approve || Object.keys(queryEdits).length > 0 || Object.keys(intentEdits).length > 0 || excludedQueries.length > 0 || excludedSources.length > 0} onClick={() => void workspace.mutate("ResearchPlan", `${base}/plans/approve`, { ...selection, confirmed_query_ids: confirmedQueries, acknowledged_gap_ids: acknowledged }, recovery("approve_plan"), "PlanMutationReceipt")} type="button">Kaydedilmiş planı ve seçili sorguları onayla</button>
            <button className={researchButton} disabled={locked || !planRecord.eligibility.can_start || !!workspace.run.data} onClick={() => void workspace.mutate("ResearchRun", `${base}/start`, selection, `${base}/run`, "ResearchRun")} type="button">Tek araştırmayı başlat</button>
            <button className={researchButton} disabled={locked || !brief} type="button" onClick={() => void workspace.mutate("PreparationAnalysisOperation", `${base}/analyses`, { kind: "plan", ...selection, budget }, `/api/v1/projects/${projectId}/analysis-operations/propose_plan/{key}`, "PreparationAnalysisOperation")}>Plan için AI niyet ve sorgu önerileri</button>
          </div>
        </> : null}
        <button className={researchButton} type="button" onClick={() => void workspace.read("ResearchPlanPage", `${base}/plans`, setPlanPage)}>Plan sürümlerini oku</button>{planPage.data ? <><ul className="space-y-2 text-sm">{planPage.data.items.map(item => <li key={`${item.research_plan_id}:${item.plan_version}`}><button className={researchButton} type="button" onClick={() => { setSelectedPlan({ data: null, status: "loading", message: null }); void workspace.read("ResearchPlanPreparation", `${base}/plans/${item.research_plan_id}/versions/${item.plan_version}`, setSelectedPlan); }}>Plan v{item.plan_version} · {item.status}</button></li>)}</ul>{planPage.data.page.next_cursor ? <button className={researchButton} type="button" onClick={() => void workspace.read("ResearchPlanPage", `${base}/plans?cursor=${encodeURIComponent(planPage.data!.page.next_cursor!)}`, setPlanPage)}>Sonraki plan sayfası</button> : null}</> : null}
        {selectedPlan?.data ? <details open><summary className="cursor-pointer text-sm font-semibold">Salt okunur plan v{selectedPlan.data.plan.plan_version}</summary><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap break-all rounded-lg bg-[var(--paper)] p-3 text-xs">{JSON.stringify(selectedPlan.data.plan, null, 2)}</pre></details> : null}
      </Card>
    </> : null}
    {view === "all" || view === "run" ? <Card title="Faz 2–3 · Kalıcı araştırma durumu"><Notice read={workspace.run} empty="Bu plan için araştırma henüz başlatılmadı." />{workspace.run.data ? <><p className="text-sm">Durum: {workspace.run.data.status} · faz: {workspace.run.data.phase}</p><Usage usage={workspace.run.data.usage} /><ul className="space-y-2">{workspace.run.data.source_executions.map(item => <li className="rounded-lg border border-[var(--line)] p-3 text-sm" key={item.execution_id}><p>{item.source_id} · {item.status} · deneme {item.attempt}</p><p className="mt-1">Keşif {item.counts.discovered} · fetched {item.counts.fetched} · normalized {item.counts.normalized} · unique {item.counts.unique} · independent {item.counts.independent} · claims {item.counts.claims}</p>{item.error ? <p className="mt-2">{item.error.code}: {item.error.message}</p> : null}<Usage usage={item.usage} /></li>)}</ul><Texts items={workspace.run.data.errors.map(item => `${item.code}: ${item.message}`)} /><button className={researchButton} type="button" disabled={locked || ["completed", "failed", "cancelled"].includes(workspace.run.data.status)} onClick={() => void workspace.mutate("ResearchRun", `${base}/cancel`, {})}>Araştırmayı iptal et</button></> : null}<p className="text-xs leading-5 text-[#686973]">Keşif metaverisi fetched içerik değildir. Erişim hatası no_results değildir. Tamamlanmış bir run’ın kanıtı yetersiz olabilir.</p></Card> : null}
    {view === "all" || ["evidence", "competitors", "problems"].includes(view) ? <Card title="Faz 2 · Kaynaklı kanıt kütüphanesi"><Notice read={workspace.bundle} empty="EvidenceBundle henüz yayımlanmadı." />{evidence ? <>
      <p className="text-sm">Bundle v{evidence.bundle_version} · {evidence.status} · {evidence.claims.length} claim · {evidence.independence.filter(item => item.status === "known").length} bilinen bağımsız grup</p><Texts items={evidence.known_unknowns} /><Texts items={evidence.limitations} />
      <label className="block text-sm">Bulguları filtrele<select className={input} value={filter} onChange={event => setFilter(event.target.value)}><option value="all">Tüm kayıtlı claim’ler</option><option value="supports">Destekleyen</option><option value="opposes">Karşıt</option><option value="relevant">İlgili</option><option value="pricing">Fiyat ve ödeme beyanı</option></select></label>
      {evidence.claims.filter(item => (view !== "competitors" || item.claim_type.startsWith("competitor_")) && (view !== "problems" || item.claim_type === "problem_report" || item.claim_type === "workaround") && (filter === "all" || filter === "relevant" && item.relevant || filter === "pricing" && ["pricing_signal", "stated_wtp_weak_signal", "observed_payment_behavior"].includes(item.claim_type) || item.direction === filter)).map(item => <article className="space-y-2 rounded-lg border border-[var(--line)] p-4" key={item.claim_id}><p className="whitespace-pre-wrap text-sm leading-6">{item.statement}</p><p className="text-xs">{item.claim_type} · {item.direction} · {item.evidence_type} · ilgili: {String(item.relevant)} · pazar: {item.market_match === null ? "unknown" : String(item.market_match)}</p><p className="break-all text-xs">Kimlik: {item.independent_identity_key ?? "unknown"} · sahiplik: {item.ownership_key ?? "unknown"}</p><Texts items={item.limitations} /><div className="flex flex-wrap gap-2">{item.citation_ids.map(identity => <button className={researchButton} type="button" key={identity} onClick={() => void readCitation(identity)}>Gerçek alıntı ve bağlam</button>)}</div></article>)}
      <details><summary className="cursor-pointer text-sm font-semibold">Kaynak raporları ve kapsama</summary><div className="mt-3 space-y-3">{evidence.source_reports.map(item => <div className="rounded-lg border border-[var(--line)] p-3 text-sm" key={item.source_report_id}><p>{item.source_id} · {item.status} · {item.stop_reason}</p><p>{item.counts.fetched} fetched · {item.counts.independent} independent</p><Texts items={item.known_unknowns} /></div>)}{evidence.coverage_assessments.map(item => <p className="text-sm" key={item.intent}>{item.intent}: {item.status} · {item.independent_groups} bağımsız grup · {item.opposing_claims} karşıt claim</p>)}</div></details>
    </> : null}</Card> : null}
    {view === "all" || view === "report" ? <Card title="Faz 3 · Araştırma raporu"><Notice read={selectedReport ?? workspace.report} empty="DecisionReport henüz yayımlanmadı." />{visibleReport ? <>
      <p className="text-lg font-semibold">{outcomeLabels[visibleReport.outcome]}</p><p className="break-all text-xs">Rapor v{visibleReport.report_version} · {visibleReport.report_id} · bundle v{visibleReport.bundle_version}</p><p className="text-sm font-semibold">Yönetici değerlendirmesi zorunlu.</p><h3 className="font-semibold">Yeterlilik: {visibleReport.sufficiency.status}</h3><p className="text-sm">{visibleReport.sufficiency.independent_examples}/3 bağımsız örnek · {visibleReport.sufficiency.independent_sources}/2 bağımsız kaynak · tez yönü: {visibleReport.sufficiency.direction}</p><p className="text-sm leading-6">{visibleReport.sufficiency.thesis}</p><dl className="grid gap-2 text-sm sm:grid-cols-2">{Object.entries(visibleReport.sufficiency.qualitative_checks).map(([name, state]) => <div key={name}><dt className="font-semibold">{name.replaceAll("_", " ")}</dt><dd>{state}</dd></div>)}</dl><Texts items={visibleReport.sufficiency.blocking_reasons} />
      <h3 className="font-semibold">Özet ve dayanak</h3>{facts(visibleReport.summary)}<h3 className="font-semibold">Karşıt kanıt</h3>{facts(visibleReport.counter_evidence)}<h3 className="font-semibold">Pazar bulguları</h3>{facts(visibleReport.market_assessment)}<h3 className="font-semibold">Problem ve müşteri</h3>{facts([...visibleReport.problem, ...visibleReport.target_customer])}<h3 className="font-semibold">Rakipler ve araştırma fırsatları</h3>{facts([...visibleReport.competitors, ...visibleReport.opportunity_hypotheses])}
      <details><summary className="cursor-pointer font-semibold">Gerekçe ve ayrı değerlendirme boyutları</summary><div className="mt-3 space-y-3">{visibleReport.rationale.map(item => <div key={item.block_id}><p className="text-sm leading-6">{item.kind}: {item.statement}</p>{item.citation_ids.map(identity => <button className={researchButton} type="button" key={identity} onClick={() => void readCitation(identity)}>Gerekçe alıntısı</button>)}</div>)}{visibleReport.pillar_profiles.map(item => <p className="text-sm" key={item.pillar}>{item.pillar}: {item.status} · destek {item.supporting_claim_ids.length} · karşıt {item.opposing_claim_ids.length}</p>)}</div></details>
      <h3 className="font-semibold">Bilinmeyenler ve sınırlar</h3><Texts items={[...visibleReport.known_unknowns, ...visibleReport.critical_unknowns, ...visibleReport.limitations]} /><h3 className="font-semibold">Varsayımlar ve kullanıcı koşulları</h3><Texts items={[...visibleReport.assumptions, ...visibleReport.execution_constraints]} /><dl className="text-sm">{Object.entries(visibleReport.user_conditions_snapshot).map(([name, value]) => <div key={name}><dt className="font-semibold">{name}</dt><dd>{value.value ?? "unknown"} · {value.origin} · onay: {String(value.confirmed)}</dd></div>)}</dl>
      {visibleReport.modification ? <div className="space-y-2 rounded-lg border border-[var(--line)] p-4 text-sm"><h3 className="font-semibold">Modify · insan onayı gereken araştırma hipotezi</h3><p>Korunan sinyal: {visibleReport.modification.preserve_signal}</p><p>Değişen varsayım: {visibleReport.modification.change_assumption}</p><p>Önerilen odak: {visibleReport.modification.proposed_focus}</p><Texts items={visibleReport.modification.evidence_to_reassess} /><p>Brief düzenleme formunda yeni insan seçimi ve yeni plan sürümü gerekir.</p></div> : null}
      <p className="text-sm">Primary doğrulama: {visibleReport.primary_validation.status} · {visibleReport.primary_validation.observation_count} gözlem</p><Texts items={visibleReport.primary_validation.unvalidated_behaviors} /><p className="text-sm">Karar hassasiyeti: {visibleReport.decision_stability.status} · yöntem: {visibleReport.decision_stability.method ?? "uygulanmadı"}</p><Texts items={visibleReport.decision_stability.assumptions_that_change_outcome} /><h3 className="font-semibold">Sonraki araştırma bilgisi</h3><Texts items={visibleReport.next_actions.map(item => `${item.kind}: ${item.question_or_hypothesis} · gereken kanıt: ${item.evidence_to_capture.join(", ")} · yeniden değerlendirme: ${item.reassessment_trigger}`)} /><Usage usage={visibleReport.usage} />
      <button className={researchButton} type="button" disabled={workspace.busy} onClick={() => void workspace.request("DecisionReport", `${base}/reports/${visibleReport.report_id}/versions/${visibleReport.report_version}/export`).then(result => { if (!result?.ok) { setDetailMessage(result && !result.ok ? result.message : "Export okunamadı."); return; } const url = URL.createObjectURL(new Blob([result.raw], { type: "application/json" })); const anchor = window.document.createElement("a"); anchor.href = url; anchor.download = `research-${result.data.report_id}-v${result.data.report_version}.json`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); })}>Bu gerçek rapor sürümünü JSON olarak indir</button>
    </> : null}
      <button className={researchButton} type="button" onClick={() => void workspace.read("DecisionReportPage", `${base}/reports`, setReportPage)}>Rapor geçmişini oku</button>{reportPage.data ? <><ul className="space-y-2">{reportPage.data.items.map(item => <li key={`${item.report_id}:${item.report_version}`}><button className={researchButton} type="button" onClick={() => { setSelectedReport({ data: null, status: "loading", message: null }); void workspace.read("DecisionReport", `${base}/reports/${item.report_id}/versions/${item.report_version}`, setSelectedReport); }}>Rapor v{item.report_version} · {outcomeLabels[item.outcome]}</button></li>)}</ul>{reportPage.data.page.next_cursor ? <button className={researchButton} type="button" onClick={() => void workspace.read("DecisionReportPage", `${base}/reports?cursor=${encodeURIComponent(reportPage.data!.page.next_cursor!)}`, setReportPage, false)}>Sonraki rapor sayfası</button> : null}<button className={researchButton} type="button" onClick={() => setSelectedReport(null)}>Güncel raporu göster</button></> : null}
      <h3 className="font-semibold">Sonlu kanıt boşlukları</h3><Notice read={workspace.gaps} empty="Gap kaydı yok." />{workspace.gaps.data?.items.map(item => <div className="space-y-2 rounded-lg border border-[var(--line)] p-4 text-sm" key={`${item.gap_id}:${item.gap_version}`}><p className="font-semibold">{item.kind} · {item.status} · cycle {item.cycle}/{item.max_cycles} · v{item.gap_version}</p><p>{item.question}</p><Texts items={item.missing_evidence} /><Texts items={item.stop_conditions} />{item.kind === "validate_primary" ? <p>Bu boşluk yönetici değerlendirmesine sunulur; web sorgusu başlatmaz.</p> : <><p>{item.proposed_queries.length} önceden onaylanmış sorgu · aynı ortak bütçenin kalanı</p><button className={researchButton} type="button" disabled={locked || item.status !== "proposed" || item.cycle >= item.max_cycles || workspace.run.data?.status !== "completed" || workspace.report.data?.report_id !== item.parent_report_id} onClick={() => void workspace.mutate("GapApprovalReceipt", `${base}/gaps/${item.gap_id}/approve`, { expected_gap_version: item.gap_version, expected_report_id: item.parent_report_id, expected_report_version: item.parent_report_version, confirmed: true }, `${base}/run`, "ResearchRun")}>Bu secondary gap’i kalan bütçeyle onayla ve çalıştır</button></>}</div>)}
    </Card> : null}
    {detailMessage || citation ? <Card title="Alıntı ve kaynak bağlamı">{detailMessage ? <p role="status" className="text-sm">{detailMessage}</p> : null}{citation ? <><blockquote className="whitespace-pre-wrap border-l-4 border-[var(--brand)] pl-4 text-sm leading-6">{citation.verbatim_quote}</blockquote><a className="block break-all text-sm text-[var(--brand-deep)] underline" href={citation.source_url} target="_blank" rel="noopener noreferrer">{citation.source_url}</a><p className="text-xs">Published: {citation.published_at ?? "unknown"} · collected: {citation.collected_at}</p><p className="break-all text-xs">Document v{citation.document_version} · {citation.validation_status} · normalizer {citation.normalization_version} · offsets {citation.start_offset}–{citation.end_offset}</p><p className="break-all text-xs">Tam metin hash: {citation.normalized_content_hash}<br />Segment hash: {citation.segment_text_hash}</p>{document ? <><p className="whitespace-pre-wrap rounded-lg bg-[var(--paper)] p-3 text-sm leading-6">{unicodeText!.slice(Math.max(0, citation.start_offset - 250), citation.start_offset).join("")}<mark>{unicodeText!.slice(citation.start_offset, citation.end_offset).join("")}</mark>{unicodeText!.slice(citation.end_offset, citation.end_offset + 250).join("")}</p><Texts items={document.quality_flags} /><a className={`${researchButton} inline-flex items-center`} href={`/api/backend${base}/artifacts/${citation.artifact_id}/content`} download>Yetkili ham içeriği indir</a></> : null}</> : null}<button className={researchButton} type="button" onClick={() => { citationSelection.current += 1; setCitation(null); setDocument(null); setDetailMessage(null); }}>Alıntı bağlamını kapat</button></Card> : null}
  </div>;
}
