"use client";

import { useState } from "react";

const competitors = [["MealDesk", "Studios & clinics", "$79/mo", "All-in-one operations", "High"], ["NutriFlow", "Independent coaches", "$39/mo", "Plan automation", "Medium"], ["Coachboard", "Wellness teams", "Custom", "Enterprise workflow", "Low"]] as const;
const levels = ["All", "High", "Medium", "Low"];
function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-xl border border-[var(--line)] bg-white ${className}`}>{children}</section>; }

export function CompetitorTable() {
  const [level, setLevel] = useState("All");
  const [selected, setSelected] = useState<string>(competitors[0][0]);
  const visible = competitors.filter((item) => level === "All" || item[4] === level);
  const active = competitors.find((item) => item[0] === selected) ?? competitors[0];
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_290px]"><div className="space-y-4"><Card className="p-4"><div className="flex items-center justify-between gap-4"><div className="flex gap-1 rounded-lg bg-[#f6f6f8] p-1">{levels.map((item) => <button className={`rounded-md px-3 py-2 text-xs font-semibold ${level === item ? "bg-white text-[var(--brand-deep)] shadow-sm" : "text-[#777883]"}`} key={item} onClick={() => setLevel(item)} type="button">{item}</button>)}</div><span className="text-xs text-[#777883]">{visible.length} tracked</span></div></Card><Card className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="border-b border-[var(--line)] bg-[#fcfcfd] text-[10px] uppercase tracking-[.1em] text-[#858690]"><tr>{["Competitor", "Target customer", "Pricing", "Positioning", "Threat"].map((head) => <th className="px-5 py-4 font-semibold" key={head}>{head}</th>)}</tr></thead><tbody>{visible.map((row) => <tr className={`cursor-pointer border-b border-[var(--line)] transition hover:bg-[#fcfcfd] ${selected === row[0] ? "bg-[var(--brand-soft)]" : ""}`} key={row[0]} onClick={() => setSelected(row[0])}>{row.map((cell, index) => <td className={`px-5 py-4 ${index === 0 ? "font-semibold text-[var(--ink)]" : "text-[#656671]"}`} key={cell}>{index === 4 ? <span className={`rounded-md px-2 py-1 font-semibold ${cell === "High" ? "bg-[var(--negative-soft)] text-[var(--negative)]" : cell === "Medium" ? "bg-[var(--warning-soft)] text-[var(--warning)]" : "bg-[var(--positive-soft)] text-[var(--positive)]"}`}>{cell}</span> : cell}</td>)}</tr>)}</tbody></table></Card></div><Card className="h-fit p-5"><p className="text-[10px] font-semibold uppercase tracking-[.13em] text-[#92939c]">Competitor profile</p><h2 className="mt-4 text-lg font-semibold tracking-[-.04em]">{active[0]}</h2><dl className="mt-5 space-y-3 border-y border-[var(--line)] py-4 text-xs">{[["Customer", active[1]], ["Pricing", active[2]], ["Positioning", active[3]], ["Threat", active[4]]].map(([label, value]) => <div className="flex justify-between gap-3" key={label}><dt className="text-[#777883]">{label}</dt><dd className="text-right font-semibold text-[var(--ink)]">{value}</dd></div>)}</dl><button className="mt-5 w-full rounded-lg border border-[var(--line)] px-3 py-2.5 text-xs font-semibold transition hover:bg-[#fafafa]" type="button">Compare against project</button></Card></div>;
}
