"use client";

import { Check, Download, Lightbulb } from "lucide-react";
import { useState } from "react";

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-xl border border-[var(--line)] bg-white ${className}`}>{children}</section>; }
export function DecisionReport() {
  const [saved, setSaved] = useState(false);
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_360px]"><Card className="p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><span className="inline-flex rounded-md bg-[var(--positive-soft)] px-2 py-1 text-[10px] font-semibold text-[var(--positive)]">BUILD · 82% CONFIDENCE</span><span className="text-xs text-[#777883]">Updated today</span></div><h2 className="mt-5 text-2xl font-semibold tracking-[-.05em]">Build with a focused entry point.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#686973]">Demand exists, but the clearest opening is a simpler and more affordable workflow for independent nutrition coaches.</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{[["Market demand", "91", "Strong"], ["Pain severity", "88", "Strong"], ["Evidence quality", "86", "Traceable"]].map(([label, value, note]) => <div className="rounded-lg bg-[#f8f8fa] p-4" key={label}><span className="block text-[11px] text-[#777883]">{label}</span><b className="mt-2 block font-mono text-xl text-[var(--ink)]">{value}/100</b><span className="mt-1 block text-[10px] text-[var(--positive)]">{note}</span></div>)}</div><div className="mt-7 border-t border-[var(--line)] pt-5"><p className="text-[10px] font-semibold uppercase tracking-[.13em] text-[#92939c]">Evidence behind the recommendation</p><div className="mt-4 space-y-3">{["High cost complaints are consistent across review sources.", "Independent coaches prefer focused workflows over all-in-one suites.", "Pricing research indicates a clear entry point below $40/month."].map((item) => <div className="flex gap-3 text-xs leading-5 text-[#686973]" key={item}><Check className="mt-0.5 h-4 w-4 shrink-0 text-[var(--positive)]" />{item}</div>)}</div></div></Card><div className="space-y-5"><Card className="p-5"><p className="text-[10px] font-semibold uppercase tracking-[.13em] text-[#92939c]">Recommended next step</p><Lightbulb className="mt-5 h-5 w-5 text-[var(--brand)]" /><h3 className="mt-3 text-sm font-semibold">Validate willingness to pay</h3><p className="mt-2 text-xs leading-5 text-[#73747e]">Interview independent coaches before treating online demand as observed payment behavior.</p><button className="mt-5 w-full rounded-lg bg-[var(--brand)] px-3 py-2.5 text-xs font-semibold text-white transition hover:bg-[var(--brand-deep)]" onClick={() => setSaved(true)} type="button">{saved ? "Added to project plan" : "Add to project plan"}</button>{saved && <p className="mt-3 text-center text-[11px] font-medium text-[var(--positive)]">Next step saved</p>}</Card><Card className="p-5"><button className="inline-flex w-full items-center justify-center gap-2 rounded-lg border border-[var(--line)] px-3 py-2.5 text-xs font-semibold transition hover:bg-[#fafafa]" type="button">Export report <Download className="h-3.5 w-3.5" /></button></Card></div></div>;
}
