import { ArrowRight, Lightbulb, ShieldCheck } from "lucide-react";
import { painPoints, screenCopy, type WorkspaceScreen } from "@/lib/mock-data/workspace";
import { ProgressIndicator } from "@/components/ui/progress-indicator";
import { NewValidationForm } from "@/components/workspace/new-validation-form";
import { ProjectsBoard } from "@/components/workspace/projects-board";
import { ResearchRun } from "@/components/workspace/research-run";
import { EvidenceLibrary } from "@/components/workspace/evidence-library";

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-xl border border-[var(--line)] bg-white ${className}`}>{children}</section>; }
function Head({ screen }: { screen: WorkspaceScreen }) { const copy = screenCopy[screen]; return <header className="motion-enter flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[.13em] text-[var(--brand-deep)]">{copy.eyebrow}</p><h1 className="mt-2 text-[30px] font-semibold tracking-[-.055em] text-[var(--ink)]">{copy.title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#686973]">{copy.description}</p></div><button className="inline-flex items-center gap-2 self-start rounded-lg bg-[var(--brand)] px-3.5 py-2.5 text-xs font-semibold text-white transition hover:bg-[var(--brand-deep)] sm:self-auto" type="button">{copy.action}<ArrowRight className="h-3.5 w-3.5" /></button></header>; }

function NewValidation() { return <NewValidationForm />; }
function Projects() { return <ProjectsBoard />; }
function Research() { return <ResearchRun />; }
function Evidence() { return <EvidenceLibrary />; }
function Competitors() { return <Card className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="border-b border-[var(--line)] bg-[#fcfcfd] text-[10px] uppercase tracking-[.1em] text-[#858690]"><tr>{["Competitor", "Target customer", "Pricing", "Positioning", "Threat"].map((head) => <th className="px-5 py-4 font-semibold" key={head}>{head}</th>)}</tr></thead><tbody>{[["MealDesk", "Studios & clinics", "$79/mo", "All-in-one operations", "High"], ["NutriFlow", "Independent coaches", "$39/mo", "Plan automation", "Medium"], ["Coachboard", "Wellness teams", "Custom", "Enterprise workflow", "Low"]].map((row) => <tr className="border-b border-[var(--line)] transition hover:bg-[#fcfcfd]" key={row[0]}>{row.map((cell, index) => <td className={`px-5 py-4 ${index === 0 ? "font-semibold text-[var(--ink)]" : "text-[#656671]"}`} key={cell}>{index === 4 ? <span className={`rounded-md px-2 py-1 ${cell === "High" ? "bg-[var(--negative-soft)] text-[var(--negative)]" : cell === "Medium" ? "bg-[var(--warning-soft)] text-[var(--warning)]" : "bg-[var(--positive-soft)] text-[var(--positive)]"}`}>{cell}</span> : cell}</td>)}</tr>)}</tbody></table></Card>; }
function PainPoints() { return <div className="grid gap-4 lg:grid-cols-3">{painPoints.map((point) => <Card className="p-5" key={point.title}><div className="flex items-center justify-between"><span className="rounded-md bg-[var(--negative-soft)] px-2 py-1 text-[10px] font-semibold text-[var(--negative)]">{point.severity} severity</span><span className="text-xs font-medium text-[var(--positive)]">{point.trend}</span></div><h2 className="mt-5 text-base font-semibold tracking-[-.03em]">{point.title}</h2><p className="mt-2 text-xs leading-5 text-[#74757f]">{point.note}</p><div className="mt-6 border-t border-[var(--line)] pt-4 text-xs"><span className="font-mono font-semibold">{point.count}</span><span className="ml-2 text-[#858690]">across reviewed sources</span></div></Card>)}</div>; }
function DecisionReports() { return <div className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_360px]"><Card className="p-6"><span className="inline-flex rounded-md bg-[var(--positive-soft)] px-2 py-1 text-[10px] font-semibold text-[var(--positive)]">BUILD · 82% CONFIDENCE</span><h2 className="mt-5 text-2xl font-semibold tracking-[-.05em]">Build with a focused entry point.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#686973]">Demand exists, but the clearest opening is a simpler and more affordable workflow for independent nutrition coaches.</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{[["Market demand", "91"], ["Pain severity", "88"], ["Evidence quality", "86"]].map(([label, value]) => <div className="rounded-lg bg-[#f8f8fa] p-4" key={label}><span className="block text-[11px] text-[#777883]">{label}</span><b className="mt-2 block font-mono text-xl">{value}/100</b></div>)}</div></Card><Card className="p-5"><p className="text-[10px] font-semibold uppercase tracking-[.13em] text-[#92939c]">Recommended next step</p><Lightbulb className="mt-5 h-5 w-5 text-[var(--brand)]" /><h3 className="mt-3 text-sm font-semibold">Validate willingness to pay</h3><p className="mt-2 text-xs leading-5 text-[#73747e]">Interview independent coaches before treating online demand as observed payment behavior.</p></Card></div>; }
function Settings() { return <div className="grid gap-5 xl:grid-cols-2"><Card className="p-6"><h2 className="text-sm font-semibold">Profile</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["Full name", "Batuhan Evleksiz"], ["Workspace", "Research workspace"], ["Default market", "Turkey"], ["Default language", "English"]].map(([label, value]) => <label className="text-xs font-medium text-[#656671]" key={label}>{label}<input className="mt-2 w-full rounded-lg border border-[var(--line)] px-3 py-2.5 text-sm text-[var(--ink)]" defaultValue={value} /></label>)}</div></Card><Card className="p-6"><h2 className="text-sm font-semibold">Research preferences</h2><div className="mt-5 space-y-4">{["Notify me when a research run completes", "Include evidence-quality warnings", "Show research plan before execution"].map((option, index) => <label className="flex items-center justify-between gap-4 text-xs" key={option}><span>{option}</span><input aria-label={option} className="h-4 w-4 accent-[var(--brand)]" defaultChecked={index !== 1} type="checkbox" /></label>)}</div></Card></div>; }
function Help() { return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[["How research works", "Understand the path from idea to decision."], ["Evidence & citations", "Learn what makes a source traceable and useful."], ["Decision confidence", "See why confidence is never a substitute for evidence."], ["Account & workspace", "Manage your project space and preferences."], ["Contact support", "Get help with your DemandRift workspace."], ["Product updates", "Read what is new in the platform."]].map(([title, detail]) => <Card className="group p-5 transition hover:-translate-y-0.5 hover:border-[#d9d9e2]" key={title}><ShieldCheck className="h-5 w-5 text-[var(--brand)]" /><h2 className="mt-5 text-sm font-semibold">{title}</h2><p className="mt-2 text-xs leading-5 text-[#73747e]">{detail}</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-semibold text-[var(--brand-deep)]">Read guide <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5" /></span></Card>)}</div>; }

export function WorkspacePage({ screen }: { screen: WorkspaceScreen }) { const content = { "new-validation": <NewValidation />, projects: <Projects />, research: <Research />, evidence: <Evidence />, competitors: <Competitors />, "pain-points": <PainPoints />, "decision-reports": <DecisionReports />, settings: <Settings />, help: <Help /> }[screen]; return <div className="space-y-7"><Head screen={screen} />{content}</div>; }
