"""Canonical three-phase wire contracts. Never accept identities generated by a model.

Pydantic definitions generate JSON Schema and TypeScript; versions are immutable.
Legacy preview enums are reused while that route remains backward compatible.
"""
from __future__ import annotations

from decimal import Decimal
from enum import StrEnum
from typing import Annotated, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, HttpUrl, SecretStr, model_validator

from app.research_plan import AddOnPackage, ClarityStatus, FieldOrigin, ResearchCategory, ResearchMode

SCHEMA_VERSION = "1.0.0"
Text = Annotated[str, Field(min_length=1, max_length=10000, pattern=r"\S")]
Name = Annotated[str, Field(min_length=1, max_length=128, pattern=r"\S")]
Version = Annotated[str, Field(min_length=1, max_length=128, pattern=r"\S")]
Hash = Annotated[str, Field(pattern=r"^[0-9a-f]{64}$")]
Positive = Annotated[int, Field(gt=0, strict=True)]
Count = Annotated[int, Field(ge=0, strict=True)]
Money = Annotated[str, Field(pattern=r"^(0|[1-9][0-9]*)\.[0-9]{6}$")]


class Contract(BaseModel):
    model_config = ConfigDict(extra="forbid", allow_inf_nan=False, validate_default=True,
                              json_schema_serialization_defaults_required=True)


class Phase(StrEnum):
    PLANNING = "planning"
    EVIDENCE = "evidence"
    DECISION = "decision"


class RunStatus(StrEnum):
    DRAFT = "draft"
    AWAITING_USER = "awaiting_user"
    PLANNED = "planned"
    QUEUED = "queued"
    ACQUIRING = "acquiring"
    NORMALIZING = "normalizing"
    ANALYZING = "analyzing"
    DECIDING = "deciding"
    COMPLETED = "completed"
    PARTIAL = "partial"
    CANCELLED = "cancelled"
    FAILED = "failed"


class SourceStatus(StrEnum):
    QUEUED = "queued"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    NO_RESULTS = "no_results"
    SOURCE_UNAVAILABLE = "source_unavailable"
    RATE_LIMITED = "rate_limited"
    BLOCKED_BY_POLICY = "blocked_by_policy"
    CHALLENGE = "challenge"
    INVALID_OUTPUT = "invalid_output"
    PARTIAL = "partial"
    CANCELLED = "cancelled"
    FAILED = "failed"


class ValidationStatus(StrEnum):
    PENDING = "pending"
    VALIDATED = "validated"
    REJECTED = "rejected"


class Direction(StrEnum):
    SUPPORTS = "supports"
    OPPOSES = "opposes"
    CONTEXT = "context"
    UNKNOWN = "unknown"


class EvidenceType(StrEnum):
    DIRECT_EXPERIENCE = "direct_experience"
    OFFICIAL_CLAIM = "official_claim"
    OBSERVED_PRICING = "observed_pricing"
    WILLINGNESS_TO_PAY = "willingness_to_pay"
    OBSERVED_PAYMENT = "observed_payment"
    OBSERVED_USAGE = "observed_usage"
    OTHER = "other"


class Outcome(StrEnum):
    POSITIVE_FINDINGS = "positive_findings"
    MODIFY = "modify"
    KILL = "kill"
    INVESTIGATE_MORE = "investigate_more"


class GapKind(StrEnum):
    INVESTIGATE_SECONDARY = "investigate_secondary"
    VALIDATE_PRIMARY = "validate_primary"


class SourceFamily(StrEnum):
    OFFICIAL_WEB = "official_web"
    TECHNICAL_COMMUNITY = "technical_community"
    MARKETPLACE_REVIEW = "marketplace_review"
    SOCIAL_COMMUNITY = "social_community"
    DOMAIN_WEB = "domain_web"
    ADS_TRENDS_BUSINESS = "ads_trends_business"
    PUBLIC_ACADEMIC_REGULATION = "public_academic_regulation"
    VERTICAL = "vertical"


class PermissionStatus(StrEnum):
    PERMITTED = "permitted"
    BLOCKED = "blocked"
    REQUIRES_AUTHORIZATION = "requires_authorization"
    UNKNOWN = "unknown"


class SourceHealth(StrEnum):
    SUPPORTED = "supported"
    QUALIFIED = "qualified"
    UNAVAILABLE = "unavailable"
    BLOCKED = "blocked"
    DEFERRED = "deferred"


class AccessMethod(StrEnum):
    API = "api"
    PERMITTED_HTTP = "permitted_http"
    MANUAL_EXPORT = "manual_export"
    ARCHIVE = "archive"


class ContentKind(StrEnum):
    DISCOVERY = "discovery"
    FETCHED_CONTENT = "fetched_content"


class SearchIntent(StrEnum):
    PROBLEM_DEMAND = "problem_demand"
    EXISTING_ALTERNATIVES = "existing_alternatives"
    DISSATISFACTION = "dissatisfaction"
    OBSERVED_MARKET_PRICING = "observed_market_pricing"
    USE_CASE = "use_case"
    COMPETITOR_DISCOVERY = "competitor_discovery"
    COUNTER_EVIDENCE = "counter_evidence"
    STATED_WTP_WEAK_SIGNAL = "stated_wtp_weak_signal"
    TECHNICAL_FEASIBILITY = "technical_feasibility"
    REGULATORY_CONSTRAINTS = "regulatory_constraints"
    ADOPTION_SIGNALS = "adoption_signals"


class FieldState(StrEnum):
    KNOWN = "known"
    INFERRED = "inferred"
    MISSING = "missing"
    CONFLICTING = "conflicting"


class Versions(Contract):
    brief: Positive | None = None
    plan: Positive | None = None
    evidence_bundle: Positive | None = None
    category_catalog: Version | None = None
    source_registry: Version | None = None
    connectors: dict[Name, Version] = Field(default_factory=dict)
    prompts: dict[Name, Version] = Field(default_factory=dict)
    model: Version | None = None
    normalizer: Version | None = None
    extractor: Version | None = None
    decision_policy: Version | None = None
    validator: Version | None = None


class Envelope(Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    user_id: UUID
    project_id: UUID
    research_id: UUID
    created_at: AwareDatetime
    versions: Versions

    def require_version_match(self, version_key: str, expected: int | str) -> None:
        recorded = getattr(self.versions, version_key)
        if recorded is not None and recorded != expected:
            raise ValueError(f"versions.{version_key} must match the record's explicit version")


class BudgetLimits(Contract):
    max_requests: Positive
    max_bytes: Positive
    max_pages: Positive
    max_records: Positive
    max_duration_seconds: Positive
    max_tokens: Positive
    max_cost_usd: Money
    soft_cost_usd: Money
    max_concurrency: Annotated[int, Field(ge=1, le=8, strict=True)]

    @model_validator(mode="after")
    def valid_cost_limits(self) -> BudgetLimits:
        if Decimal(self.soft_cost_usd) > Decimal(self.max_cost_usd):
            raise ValueError("soft_cost_usd cannot exceed max_cost_usd")
        return self


class Usage(Contract):
    requests: Count = 0
    bytes: Count = 0
    pages: Count = 0
    records: Count = 0
    duration_seconds: Annotated[float, Field(ge=0)] = 0
    input_tokens: Count = 0
    output_tokens: Count = 0
    cost_usd: Money = "0.000000"
    reserved_cost_usd: Money = "0.000000"
    provider_result_unknown: bool = False


class ProvenanceField(Contract):
    value: Text | None = None
    state: FieldState = FieldState.MISSING
    origin: FieldOrigin | None = None
    assumption_id: Name | None = None
    conflicting_values: list[Text] = Field(default_factory=list)
    prior_origins: list[FieldOrigin] = Field(default_factory=list)
    confirmed: bool = False

    @model_validator(mode="after")
    def unknowns_and_confirmation(self) -> ProvenanceField:
        if self.state == FieldState.MISSING and self.value is not None:
            raise ValueError("missing state cannot assert a value")
        if self.state in (FieldState.KNOWN, FieldState.INFERRED) and self.value is None:
            raise ValueError("known/inferred state needs a value")
        if self.state == FieldState.INFERRED and self.origin not in (FieldOrigin.AI_INFERRED, FieldOrigin.AI_HYPOTHESIS):
            raise ValueError("inferred state needs AI provenance")
        if self.state == FieldState.CONFLICTING and (self.value is not None or len(self.conflicting_values) < 2):
            raise ValueError("conflicting state keeps candidates without asserting one as fact")
        if self.state != FieldState.CONFLICTING and self.conflicting_values:
            raise ValueError("only conflicting fields contain conflicting_values")
        if self.value is None and (self.origin is not None or self.confirmed):
            raise ValueError("unknown value has no asserted origin or confirmation")
        if self.value is not None and self.origin is None:
            raise ValueError("known value needs provenance")
        if self.origin == FieldOrigin.USER_CONFIRMED and not self.confirmed:
            raise ValueError("user_confirmed origin needs confirmation")
        if self.origin in (FieldOrigin.AI_INFERRED, FieldOrigin.AI_HYPOTHESIS) and self.assumption_id is None:
            raise ValueError("AI-derived fields need a traceable assumption_id")
        return self


class BriefContent(Contract):
    original_idea: Annotated[str, Field(min_length=1, max_length=10000, pattern=r"\S")]
    normalized_idea: Text | None = None
    product_type: ProvenanceField = Field(default_factory=ProvenanceField)
    target_user: ProvenanceField = Field(default_factory=ProvenanceField)
    problem_or_job: ProvenanceField = Field(default_factory=ProvenanceField)
    context_or_niche: ProvenanceField = Field(default_factory=ProvenanceField)
    market_scope: ProvenanceField = Field(default_factory=ProvenanceField)
    business_model: ProvenanceField = Field(default_factory=ProvenanceField)
    alternatives: ProvenanceField = Field(default_factory=ProvenanceField)
    constraints: dict[Name, ProvenanceField] = Field(default_factory=dict)
    clarity_status: ClarityStatus
    missing_fields: list[Name] = Field(default_factory=list)
    clarifying_questions: Annotated[list[Text], Field(max_length=3)] = Field(default_factory=list)
    assumption_ids: list[Name] = Field(default_factory=list)
    skipped_clarification: bool = False
    continue_with_unknowns: bool = False
    language_scope: Annotated[list[Name], Field(min_length=1, max_length=8)]
    primary_category: ResearchCategory | None = None
    category_origin: FieldOrigin | None = None
    category_confirmed: bool = False
    add_on_packages: list[AddOnPackage] = Field(default_factory=list)
    secondary_categories: list[ResearchCategory] = Field(default_factory=list)
    modifiers: list[Name] = Field(default_factory=list)
    category_rationale: Text | None = None
    known_unknowns: list[Text] = Field(default_factory=list)

    @model_validator(mode="after")
    def category_and_language_consistency(self) -> BriefContent:
        if self.primary_category is None and (self.category_origin is not None or self.category_confirmed):
            raise ValueError("unmatched category has no origin or confirmation")
        if self.primary_category is not None and self.category_origin is None:
            raise ValueError("category needs provenance")
        if self.category_origin == FieldOrigin.USER_CONFIRMED and not self.category_confirmed:
            raise ValueError("user_confirmed category origin needs confirmation")
        if len(self.language_scope) != len(set(self.language_scope)) or len(self.add_on_packages) != len(set(self.add_on_packages)):
            raise ValueError("language_scope and add_on_packages must be unique")
        if self.skipped_clarification and not self.continue_with_unknowns:
            raise ValueError("skipped clarification requires an explicit continue_with_unknowns preference")
        return self


class ResearchIntent(Contract):
    intent_id: UUID
    intent: SearchIntent
    question: Text
    priority: Annotated[int, Field(ge=1, le=5, strict=True)]
    brief_basis: list[Name]
    expected_fields: list[Name]
    required_evidence_types: list[EvidenceType]
    validation_kind: GapKind
    included: bool
    exclusion_reason: Text | None = None

    @model_validator(mode="after")
    def excluded_intent_has_reason(self) -> ResearchIntent:
        if not self.included and self.exclusion_reason is None:
            raise ValueError("excluded research intent needs a reason")
        return self


class SourceLimits(Contract):
    max_items: Positive
    max_pages: Positive
    max_requests: Positive
    max_response_bytes: Positive
    max_total_bytes: Positive
    max_seconds: Positive
    max_retries: Annotated[int, Field(ge=0, le=3, strict=True)]
    max_llm_tokens: Count


class ExtractionField(Contract):
    name: Name
    value_type: Literal["text", "integer", "number", "date", "url", "boolean"]
    required: bool
    locator: Text


class IdeaBrief(Envelope):
    brief_id: UUID
    brief_version: Positive
    status: Literal["draft", "awaiting_user", "confirmed"]
    content: BriefContent

    @model_validator(mode="after")
    def version_consistency(self) -> IdeaBrief:
        self.require_version_match("brief", self.brief_version)
        return self


class SourcePlanItem(Contract):
    source_id: Name
    profile_version: Version
    connector_id: Name
    connector_version: Version
    family: SourceFamily
    permission: PermissionStatus
    health: SourceHealth
    access_method: AccessMethod
    allowed_origins: Annotated[list[HttpUrl], Field(min_length=1, max_length=16)]
    surface_id: Name
    capabilities: list[Literal["search", "fetch", "metadata", "reviews", "archive"]]
    allowed_content_types: Annotated[list[Name], Field(min_length=1)]
    eligible_categories: list[ResearchCategory]
    supported_intents: list[SearchIntent]
    extract_fields: list[ExtractionField]
    access_policy_version: Version
    retention_policy_version: Version
    rate_limit_policy_version: Version
    access_reviewed_at: AwareDatetime
    fallback_source_ids: list[Name]
    limits: SourceLimits
    expected_fields: list[Name]
    language_scope: list[Name]
    market_scope: Text | None
    ownership_key: Name | None
    limitations: list[Text]


class QueryPlanItem(Contract):
    query_id: UUID
    intent_id: UUID
    question: Text
    intent: SearchIntent
    source_id: Name
    query_text: Annotated[str, Field(min_length=1, max_length=1000, pattern=r"\S")]
    language: Name
    market_scope: Text | None
    origin: FieldOrigin
    user_confirmed: bool
    query_kind: Literal["local_index", "fulltext", "site_search", "opensearch", "api"]
    surface_id: Name
    priority: Annotated[int, Field(ge=1, le=5, strict=True)]
    expected_fields: list[Name]
    origin_refs: list[Name]
    limits: SourceLimits

    @model_validator(mode="after")
    def confirmation_is_consistent(self) -> QueryPlanItem:
        if self.origin == FieldOrigin.USER_CONFIRMED and not self.user_confirmed:
            raise ValueError("user_confirmed query origin needs confirmation")
        return self


class ResearchPlan(Envelope):
    research_plan_id: UUID
    plan_version: Positive
    plan_fingerprint: Hash
    status: Literal["draft", "awaiting_user", "confirmed"]
    brief_id: UUID
    brief_version: Positive
    brief: BriefContent
    research_mode: ResearchMode
    intents: list[ResearchIntent] = Field(default_factory=list)
    source_plan: Annotated[list[SourcePlanItem], Field(max_length=128)]
    query_plan: Annotated[list[QueryPlanItem], Field(max_length=512)]
    budget: BudgetLimits
    known_unknowns: list[Text]
    confirmed_at: AwareDatetime | None = None

    @model_validator(mode="after")
    def approved_execution_scope(self) -> ResearchPlan:
        self.require_version_match("brief", self.brief_version)
        self.require_version_match("plan", self.plan_version)
        source_ids = [s.source_id for s in self.source_plan]
        if len(source_ids) != len(set(source_ids)):
            raise ValueError("duplicate source plan identity")
        if len({q.query_id for q in self.query_plan}) != len(self.query_plan):
            raise ValueError("duplicate query identity")
        if any(q.source_id not in source_ids for q in self.query_plan):
            raise ValueError("query must reference a planned source")
        intent_ids = {i.intent_id for i in self.intents if i.included}
        if len({i.intent_id for i in self.intents}) != len(self.intents):
            raise ValueError("duplicate research intent identity")
        if any(q.intent_id not in intent_ids for q in self.query_plan):
            raise ValueError("query must reference an included research intent")
        sources = {s.source_id: s for s in self.source_plan}
        intents = {i.intent_id: i for i in self.intents}
        for source in self.source_plan:
            if source.limits.max_requests > self.budget.max_requests or source.limits.max_total_bytes > self.budget.max_bytes or source.limits.max_pages > self.budget.max_pages or source.limits.max_items > self.budget.max_records or source.limits.max_seconds > self.budget.max_duration_seconds or source.limits.max_llm_tokens > self.budget.max_tokens:
                raise ValueError("source limits cannot exceed run budget")
        for query in self.query_plan:
            source = sources[query.source_id]
            if query.intent != intents[query.intent_id].intent:
                raise ValueError("query intent must match its referenced intent")
            if query.surface_id != source.surface_id or query.intent not in source.supported_intents:
                raise ValueError("query must use the planned surface and supported intent")
            if query.language not in self.brief.language_scope or query.language not in source.language_scope:
                raise ValueError("query language must match brief and source scope")
            for key in SourceLimits.model_fields:
                if getattr(query.limits, key) > getattr(source.limits, key):
                    raise ValueError("query limits cannot exceed source profile limits")
        if (self.status == "confirmed") != (self.confirmed_at is not None):
            raise ValueError("confirmed status and timestamp must agree")
        if self.status == "confirmed":
            if any(s.permission != PermissionStatus.PERMITTED or s.health not in (SourceHealth.SUPPORTED, SourceHealth.QUALIFIED) for s in self.source_plan):
                raise ValueError("confirmed plan cannot execute an unqualified or unpermitted source")
            if self.brief.clarity_status == ClarityStatus.NEEDS_CLARIFICATION:
                raise ValueError("unresolved clarification cannot execute")
            if self.brief.primary_category is None or not self.brief.category_confirmed:
                raise ValueError("confirmed plan needs a confirmed matched category")
            values = [getattr(self.brief, name) for name in ("product_type", "target_user", "problem_or_job", "context_or_niche", "market_scope", "business_model", "alternatives")]
            values.extend(self.brief.constraints.values())
            if any(v.origin == FieldOrigin.AI_HYPOTHESIS and not v.confirmed for v in values):
                raise ValueError("unconfirmed hypothesis cannot seed scope")
            if any(q.origin == FieldOrigin.AI_HYPOTHESIS and not q.user_confirmed for q in self.query_plan):
                raise ValueError("unconfirmed query hypothesis cannot execute")
        return self


class SourceCounts(Contract):
    discovered: Count = 0
    fetched: Count = 0
    normalized: Count = 0
    eligible: Count = 0
    unique: Count = 0
    independent: Count = 0
    claims: Count = 0

    @model_validator(mode="after")
    def ordered_counts(self) -> SourceCounts:
        if not self.discovered >= self.fetched >= self.normalized >= self.eligible >= self.unique >= self.independent:
            raise ValueError("counts must follow discovered/fetched/normalized/eligible/unique/independent order")
        return self


class ApiError(Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    code: Name
    message: Text
    request_id: UUID
    operation: Name | None = None
    stage: Phase | None = None
    query_id: UUID | None = None
    details_ref: Name | None = None
    source_id: Name | None = None
    retryable: bool = False
    retry_after_seconds: Count | None = None
    usage: Usage | None = None
    remaining_work: list[Text] = Field(default_factory=list)
    next_step: Text | None = None


class QueryExecution(Envelope):
    execution_id: UUID
    query_id: UUID
    source_id: Name
    attempt: Positive
    status: SourceStatus
    counts: SourceCounts
    usage: Usage
    error: ApiError | None = None
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = None


class RawArtifact(Envelope):
    artifact_id: UUID
    execution_id: UUID
    query_id: UUID
    source_id: Name
    source_url: HttpUrl
    fetched_url: HttpUrl | None = None
    collected_at: AwareDatetime
    published_at: AwareDatetime | None = None
    archive_captured_at: AwareDatetime | None = None
    license_or_restriction: Text | None = None
    research_plan_version: Positive
    access_method: AccessMethod
    artifact_origin: Literal["live_capture", "archive_copy"]
    content_kind: ContentKind
    status: SourceStatus
    body_ref: Annotated[str, Field(min_length=1, max_length=512)] | None = None
    content_hash: Hash | None = None
    byte_count: Count
    media_type: Name | None = None
    connector_version: Version
    fields: dict[Name, Text | None] = Field(default_factory=dict)
    error: ApiError | None = None

    @model_validator(mode="after")
    def inspectable_content(self) -> RawArtifact:
        self.require_version_match("plan", self.research_plan_version)
        connector = self.versions.connectors.get(self.source_id)
        if connector is not None and connector != self.connector_version:
            raise ValueError("connector version must match source version snapshot")
        if self.access_method == AccessMethod.ARCHIVE and self.artifact_origin != "archive_copy":
            raise ValueError("archive capture must retain archive provenance")
        if self.status == SourceStatus.SUCCEEDED and self.content_kind == ContentKind.FETCHED_CONTENT:
            if self.body_ref is None or self.content_hash is None or self.byte_count == 0:
                raise ValueError("successful fetched content needs inspectable bytes and hash")
        return self


class TextSegment(Envelope):
    segment_id: UUID
    document_id: UUID
    segment_type: Literal["body", "title", "review", "comment", "quote", "other"]
    text: Annotated[str, Field(min_length=1, max_length=2000000)]
    start_offset: Count
    end_offset: Positive
    text_hash: Hash
    normalized_content_hash: Hash
    source_locator: Name | None = None
    normalization_version: Version

    @model_validator(mode="after")
    def valid_span(self) -> TextSegment:
        self.require_version_match("normalizer", self.normalization_version)
        if self.end_offset - self.start_offset != len(self.text):
            raise ValueError("segment offsets use Unicode code points and must span the text")
        return self


class NormalizedDocument(Envelope):
    document_id: UUID
    artifact_id: UUID
    external_id: Name | None = None
    document_type: Literal["article", "review", "comment", "api_record", "official_page", "other"]
    title: Text | None = None
    body_original_ref: Text
    canonical_url: HttpUrl | None = None
    parent_document_id: UUID | None = None
    author_reference: Name | None = None
    collected_at: AwareDatetime
    updated_at: AwareDatetime | None = None
    locale: Name | None = None
    engagement_metadata: dict[Name, int | str | None] = Field(default_factory=dict)
    supersedes_document_id: UUID | None = None
    document_version: Positive
    status: Literal["normalized", "rejected"]
    normalized_text: Annotated[str, Field(max_length=2000000)]
    normalized_content_hash: Hash
    normalization_version: Version
    language: Name | None
    published_at: AwareDatetime | None
    source_url: HttpUrl
    segments: list[TextSegment]
    exact_duplicate_of: UUID | None = None
    near_duplicate_of: UUID | None = None
    independent_identity_key: Name | None = None
    ownership_key: Name | None = None
    quality_flags: list[Name] = Field(default_factory=list)

    @model_validator(mode="after")
    def segment_lineage(self) -> NormalizedDocument:
        self.require_version_match("normalizer", self.normalization_version)
        ids = [s.segment_id for s in self.segments]
        if len(ids) != len(set(ids)):
            raise ValueError("duplicate segment identity")
        for s in self.segments:
            if (s.user_id, s.project_id, s.research_id, s.document_id) != (self.user_id, self.project_id, self.research_id, self.document_id):
                raise ValueError("segment lineage must match its document")
            if s.normalization_version != self.normalization_version or s.normalized_content_hash != self.normalized_content_hash or self.normalized_text[s.start_offset:s.end_offset] != s.text:
                raise ValueError("segment text/version must match the full normalized text")
        return self


class Claim(Envelope):
    claim_id: UUID
    claim_version: Positive
    claim_type: Literal["problem_report", "workaround", "feature_request", "competitor_complaint", "competitor_praise", "pricing_signal", "stated_wtp_weak_signal", "observed_payment_behavior", "switching_signal", "market_signal", "counter_evidence"]
    subject_entity: Name | None = None
    intent_ids: list[UUID]
    independence_group_ids: list[UUID]
    thesis: Text
    statement: Text
    direction: Direction
    evidence_type: EvidenceType
    citation_ids: Annotated[list[UUID], Field(min_length=1)]
    validation_status: ValidationStatus
    relevant: bool
    market_match: bool | None
    independent_identity_key: Name | None
    ownership_key: Name | None
    limitations: list[Text]

    @model_validator(mode="after")
    def citation_ids_are_unique(self) -> Claim:
        if len(self.citation_ids) != len(set(self.citation_ids)):
            raise ValueError("duplicate claim citation binding")
        return self


class Citation(Envelope):
    citation_id: UUID
    claim_ids: Annotated[list[UUID], Field(min_length=1)]
    artifact_id: UUID
    document_id: UUID
    document_version: Positive
    segment_id: UUID
    source_id: Name
    verbatim_quote: Annotated[str, Field(min_length=1, max_length=10000)]
    start_offset: Count
    end_offset: Positive
    segment_text_hash: Hash
    normalized_content_hash: Hash
    normalization_version: Version
    source_url: HttpUrl
    collected_at: AwareDatetime
    published_at: AwareDatetime | None = None
    validation_status: ValidationStatus
    validated_at: AwareDatetime | None = None
    rejection_reason: Text | None = None

    @model_validator(mode="after")
    def quote_span_and_validation(self) -> Citation:
        self.require_version_match("normalizer", self.normalization_version)
        if len(self.claim_ids) != len(set(self.claim_ids)):
            raise ValueError("duplicate citation claim binding")
        if self.end_offset - self.start_offset != len(self.verbatim_quote):
            raise ValueError("quote offsets must span the exact Unicode quote")
        if self.validation_status == ValidationStatus.VALIDATED and self.validated_at is None:
            raise ValueError("validated citation needs validation timestamp")
        if self.validation_status == ValidationStatus.REJECTED and self.rejection_reason is None:
            raise ValueError("rejected citation needs a reason")
        return self


class SourceReport(Envelope):
    source_report_id: UUID
    source_id: Name
    query_ids: list[UUID]
    coverage: dict[Name, list[Name]]
    stop_reason: Literal["completed", "coverage_reached", "no_new_evidence", "exhausted_results", "budget_exhausted", "time_exhausted", "no_eligible_sources", "cancelled", "error"]
    status: SourceStatus
    counts: SourceCounts
    claim_ids: list[UUID]
    citation_ids: list[UUID]
    supporting_claim_ids: list[UUID]
    opposing_claim_ids: list[UUID]
    known_unknowns: list[Text]
    limitations: list[Text]
    usage: Usage
    errors: list[ApiError]


class DocumentRelation(Contract):
    relation_id: UUID
    from_id: UUID
    to_id: UUID
    relation_type: Literal["duplicate_of", "repost_of", "comment_on", "quote_of", "derived_from", "same_entity_candidate"]
    method: Name
    review_status: Literal["confirmed", "candidate", "rejected"]


class IndependenceGroup(Contract):
    group_id: UUID
    claim_ids: list[UUID]
    document_ids: list[UUID]
    status: Literal["known", "unknown"]
    reason: Text
    identity_key: Name | None
    ownership_key: Name | None


class CoverageAssessment(Contract):
    intent: SearchIntent
    status: Literal["covered", "partial", "missing"]
    independent_groups: Count
    independent_source_families: Count
    supporting_claims: Count
    opposing_claims: Count
    languages: list[Name]
    markets: list[Text]
    earliest_published_at: AwareDatetime | None
    latest_published_at: AwareDatetime | None
    rule_version: Version
    limitations: list[Text]


class EvidenceMapEntry(Contract):
    name: Text
    assessment: Text | None
    status: Literal["evidenced", "unknown"]
    evidence_type: EvidenceType | None
    claim_ids: list[UUID]
    limitations: list[Text]

    @model_validator(mode="after")
    def evidenced_map_has_binding(self) -> EvidenceMapEntry:
        if self.status == "evidenced" and not self.claim_ids:
            raise ValueError("evidenced map entries need claim bindings")
        return self


class EvidenceMaps(Contract):
    problems: list[EvidenceMapEntry] = Field(default_factory=list)
    voice_of_customer: list[EvidenceMapEntry] = Field(default_factory=list)
    competitors: list[EvidenceMapEntry] = Field(default_factory=list)
    pricing: list[EvidenceMapEntry] = Field(default_factory=list)
    opportunity_hypotheses: list[EvidenceMapEntry] = Field(default_factory=list)
    market_maturity: Literal["existing", "resegmented", "emerging", "new", "unknown"] = "unknown"
    market_maturity_claim_ids: list[UUID] = Field(default_factory=list)
    market_maturity_limitations: list[Text] = Field(default_factory=list)


class EvidenceBundle(Envelope):
    bundle_id: UUID
    bundle_version: Positive
    status: Literal["complete", "partial", "insufficient"]
    source_reports: list[SourceReport]
    claims: list[Claim]
    citations: list[Citation]
    coverage: dict[SearchIntent, list[Name]]
    coverage_assessments: list[CoverageAssessment] = Field(default_factory=list)
    independence: list[IndependenceGroup] = Field(default_factory=list)
    relations: list[DocumentRelation] = Field(default_factory=list)
    evidence_maps: EvidenceMaps = Field(default_factory=EvidenceMaps)
    selection_trace_ref: Text | None = None
    source_registry_version: Version
    parent_bundle_id: UUID | None = None
    gap_ids: list[UUID] = Field(default_factory=list)
    duplicate_document_ids: list[UUID]
    known_unknowns: list[Text]
    limitations: list[Text]
    usage: Usage

    @model_validator(mode="after")
    def evidence_bindings(self) -> EvidenceBundle:
        self.require_version_match("evidence_bundle", self.bundle_version)
        claims = {c.claim_id: c for c in self.claims}
        citations = {c.citation_id: c for c in self.citations}
        if len(claims) != len(self.claims) or len(citations) != len(self.citations):
            raise ValueError("duplicate evidence identity")
        if len({report.source_report_id for report in self.source_reports}) != len(self.source_reports):
            raise ValueError("duplicate source report identity")
        for record in [*self.source_reports, *self.claims, *self.citations]:
            if (record.user_id, record.project_id, record.research_id) != (self.user_id, self.project_id, self.research_id):
                raise ValueError("bundle cannot contain foreign evidence")
        for claim in self.claims:
            if claim.validation_status != ValidationStatus.VALIDATED:
                raise ValueError("bundle claims must be validated")
            if any(cid not in citations or claim.claim_id not in citations[cid].claim_ids for cid in claim.citation_ids):
                raise ValueError("claim citation bindings must be bidirectional")
        for citation in self.citations:
            if citation.validation_status != ValidationStatus.VALIDATED:
                raise ValueError("bundle citations must be validated")
            if any(cid not in claims or citation.citation_id not in claims[cid].citation_ids for cid in citation.claim_ids):
                raise ValueError("citation claim bindings must be bidirectional")
        for report in self.source_reports:
            if any(cid not in claims for cid in report.claim_ids) or any(cid not in citations for cid in report.citation_ids):
                raise ValueError("source report cannot reference absent evidence")
            if any(citations[cid].source_id != report.source_id for cid in report.citation_ids):
                raise ValueError("source report citations must belong to its source")
            if any(not set(claims[cid].citation_ids).intersection(report.citation_ids) for cid in report.claim_ids):
                raise ValueError("source report claims need a citation from that source report")
            if any(cid not in report.claim_ids for cid in [*report.supporting_claim_ids, *report.opposing_claim_ids]):
                raise ValueError("source report directions must reference its claims")
            if any(claims[cid].direction != Direction.SUPPORTS for cid in report.supporting_claim_ids) or any(claims[cid].direction != Direction.OPPOSES for cid in report.opposing_claim_ids):
                raise ValueError("source report direction must match its actual claim")
        for group in self.independence:
            if any(cid not in claims for cid in group.claim_ids):
                raise ValueError("independence group cannot reference absent claims")
        entries = [entry for key in ("problems", "voice_of_customer", "competitors", "pricing", "opportunity_hypotheses") for entry in getattr(self.evidence_maps, key)]
        if any(cid not in claims for entry in entries for cid in entry.claim_ids):
            raise ValueError("evidence maps cannot reference absent claims")
        if any(cid not in claims for cid in self.evidence_maps.market_maturity_claim_ids):
            raise ValueError("market maturity cannot reference absent claims")
        return self


class SufficiencyAssessment(Contract):
    status: Literal["sufficient", "insufficient"]
    thesis: Text
    direction: Direction
    independent_examples: Count
    independent_sources: Count
    minimum_examples: Literal[3] = 3
    minimum_sources: Literal[2] = 2
    qualitative_checks: dict[Name, Literal["passed", "failed", "unknown"]]
    blocking_reasons: list[Text]
    eligible_outcomes: Annotated[list[Outcome], Field(min_length=1)]
    policy_version: Version


class ResearchGapRequest(Envelope):
    gap_id: UUID
    gap_version: Positive
    parent_bundle_id: UUID
    parent_bundle_version: Positive
    parent_report_id: UUID | None = None
    parent_report_version: Positive | None = None
    intent_id: UUID | None = None
    severity: Literal["critical", "high", "medium", "low"]
    eligible_source_ids: list[Name]
    expected_evidence_type: EvidenceType | None
    kind: GapKind
    question: Text
    missing_evidence: list[Text]
    proposed_queries: list[QueryPlanItem]
    remaining_budget: BudgetLimits | None
    cycle: Count
    max_cycles: Annotated[int, Field(ge=0, le=3, strict=True)]
    stop_conditions: Annotated[list[Text], Field(min_length=1)]
    status: Literal["proposed", "approved", "running", "closed", "stopped"]

    @model_validator(mode="after")
    def finite_secondary_only(self) -> ResearchGapRequest:
        if (self.parent_bundle_id is None) != (self.parent_bundle_version is None) or (self.parent_report_id is None) != (self.parent_report_version is None):
            raise ValueError("gap parent identities and versions must be supplied together")
        if self.cycle > self.max_cycles:
            raise ValueError("gap cycle cannot exceed its limit")
        if self.kind == GapKind.VALIDATE_PRIMARY and self.proposed_queries:
            raise ValueError("primary validation cannot dispatch web queries")
        return self


class ReportStatement(Contract):
    text: Text
    claim_ids: Annotated[list[UUID], Field(min_length=1)]
    citation_ids: Annotated[list[UUID], Field(min_length=1)]


class RationaleBlock(Contract):
    block_id: UUID
    statement: Text
    kind: Literal["evidence_interpretation", "assumption", "recommendation", "limitation"]
    claim_ids: list[UUID]
    citation_ids: list[UUID]

    @model_validator(mode="after")
    def facts_have_evidence(self) -> RationaleBlock:
        if self.kind == "evidence_interpretation" and (not self.claim_ids or not self.citation_ids):
            raise ValueError("factual rationale needs claim and citation bindings")
        return self


class PillarProfile(Contract):
    pillar: Literal["problem", "customer", "competition", "opportunity", "feasibility", "evidence_quality"]
    status: Literal["strong", "mixed", "weak", "insufficient"]
    supporting_claim_ids: list[UUID]
    opposing_claim_ids: list[UUID]
    known_unknowns: list[Text]


class PrimaryValidation(Contract):
    status: Literal["not_started", "partial", "available"] = "not_started"
    observation_refs: list[UUID] = Field(default_factory=list)
    observation_count: Count = 0
    unvalidated_behaviors: list[Text] = Field(default_factory=list)


class DecisionStability(Contract):
    status: Literal["stable", "sensitive", "fragile", "not_evaluated"] = "not_evaluated"
    method: Name | None = None
    critical_claim_ids: list[UUID] = Field(default_factory=list)
    assumptions_that_change_outcome: list[Text] = Field(default_factory=list)

    @model_validator(mode="after")
    def measured_stability_has_method(self) -> DecisionStability:
        if self.status != "not_evaluated" and self.method is None:
            raise ValueError("evaluated stability needs a recorded method")
        return self


class NextAction(Contract):
    action_id: UUID
    kind: Literal["secondary_research", "report_primary_gap", "management_review", "reassess"]
    target_segment: Text | None
    question_or_hypothesis: Text
    evidence_to_capture: list[Text]
    priority_reason: Text
    reassessment_trigger: Text


class Modification(Contract):
    preserve_signal: Text
    change_assumption: Text
    proposed_focus: Text
    avoid: list[Text]
    evidence_to_reassess: list[Text]
    basis_claim_ids: list[UUID]
    assumptions: list[Text]


class Investigation(Contract):
    subtype: Literal["investigate_secondary", "validate_primary", "mixed"]
    gap_ids: Annotated[list[UUID], Field(min_length=1)]
    priority_reason: Text


class ReportValidation(Contract):
    schema_check: Literal["passed"]
    identity: Literal["passed"]
    source_binding: Literal["passed"]
    outcome_policy: Literal["passed"]
    scope: Literal["passed"]
    validator_version: Version


class DecisionReport(Envelope):
    report_id: UUID
    report_version: Positive
    previous_report_id: UUID | None = None
    bundle_id: UUID
    bundle_version: Positive
    outcome: Outcome
    status: Literal["published"]
    management_review_required: Literal[True] = True
    market_assessment: list[ReportStatement]
    summary: list[ReportStatement]
    rationale: list[RationaleBlock]
    counter_evidence: list[ReportStatement]
    known_unknowns: list[Text]
    limitations: list[Text]
    sufficiency: SufficiencyAssessment
    gap_ids: list[UUID]
    pillar_profiles: list[PillarProfile]
    target_customer: list[ReportStatement]
    problem: list[ReportStatement]
    competitors: list[ReportStatement]
    opportunity_hypotheses: list[ReportStatement]
    supporting_claim_ids: list[UUID]
    opposing_claim_ids: list[UUID]
    citation_ids: list[UUID]
    critical_unknowns: list[Text]
    assumptions: list[Text]
    execution_constraints: list[Text]
    user_conditions_snapshot: dict[Name, ProvenanceField]
    primary_validation: PrimaryValidation
    decision_stability: DecisionStability
    next_actions: list[NextAction]
    modification: Modification | None
    investigation: Investigation | None
    usage: Usage
    validation: ReportValidation
    errors: list[ApiError]

    @model_validator(mode="after")
    def eligible_outcome(self) -> DecisionReport:
        self.require_version_match("evidence_bundle", self.bundle_version)
        self.require_version_match("decision_policy", self.sufficiency.policy_version)
        self.require_version_match("validator", self.validation.validator_version)
        if self.outcome not in self.sufficiency.eligible_outcomes:
            raise ValueError("outcome must be permitted by deterministic sufficiency policy")
        if self.sufficiency.status == "insufficient" and self.outcome != Outcome.INVESTIGATE_MORE:
            raise ValueError("insufficient evidence cannot publish a definitive assessment")
        if (self.outcome == Outcome.MODIFY) != (self.modification is not None):
            raise ValueError("modification must exist exactly for Modify outcome")
        if (self.outcome == Outcome.INVESTIGATE_MORE) != (self.investigation is not None):
            raise ValueError("investigation must exist exactly for Investigate More outcome")
        if self.investigation and set(self.investigation.gap_ids) != set(self.gap_ids):
            raise ValueError("investigation must reference this report's gaps")
        return self


class ResearchRun(Envelope):
    status: RunStatus
    phase: Phase
    brief_id: UUID
    brief_version: Positive
    research_plan_id: UUID
    plan_version: Positive
    plan_fingerprint: Hash
    budget: BudgetLimits
    usage: Usage
    cancel_requested: bool
    source_executions: list[QueryExecution]
    bundle_id: UUID | None = None
    report_id: UUID | None = None
    errors: list[ApiError] = Field(default_factory=list)
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = None

    @model_validator(mode="after")
    def execution_lineage_and_versions(self) -> ResearchRun:
        self.require_version_match("brief", self.brief_version)
        self.require_version_match("plan", self.plan_version)
        if len({e.execution_id for e in self.source_executions}) != len(self.source_executions):
            raise ValueError("duplicate source execution identity")
        for execution in self.source_executions:
            if (execution.user_id, execution.project_id, execution.research_id) != (self.user_id, self.project_id, self.research_id):
                raise ValueError("run cannot contain foreign source execution")
            if execution.versions.plan is not None and execution.versions.plan != self.plan_version:
                raise ValueError("source execution must retain the run plan version")
        return self


class User(Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    user_id: UUID
    email: Annotated[str, Field(min_length=3, max_length=254)]
    created_at: AwareDatetime


class Session(Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    user: User
    expires_at: AwareDatetime
    csrf_token: Hash


class AuthCredentials(Contract):
    email: Annotated[str, Field(min_length=3, max_length=254, strict=True)]
    password: Annotated[SecretStr, Field(min_length=15, max_length=128)]


class ProjectCreate(Contract):
    name: Annotated[str, Field(min_length=1, max_length=200, pattern=r"\S", strict=True)]


class Project(Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    project_id: UUID
    user_id: UUID
    name: Annotated[str, Field(min_length=1, max_length=200, pattern=r"\S")]
    created_at: AwareDatetime
    archived_at: AwareDatetime | None = None


class PageInfo(Contract):
    next_cursor: Annotated[str, Field(max_length=512)] | None = None
    limit: Annotated[int, Field(ge=1, le=100, strict=True)]


class ProjectPage(Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    items: list[Project]
    page: PageInfo


class RunPage(Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    items: list[ResearchRun]
    page: PageInfo


class ResearchCreate(Contract):
    model_config = ConfigDict(json_schema_serialization_defaults_required=False)
    original_idea: Annotated[str, Field(min_length=1, max_length=10000, pattern=r"\S", strict=True)]
    language_scope: Annotated[list[Name], Field(min_length=1, max_length=8)] = Field(default_factory=lambda: ["tr"])

    @model_validator(mode="after")
    def unique_languages(self):
        if len(set(self.language_scope)) != len(self.language_scope):
            raise ValueError("languages must be unique")
        return self


class HumanBriefPatch(Contract):
    model_config = ConfigDict(json_schema_serialization_defaults_required=False)
    expected_brief_version: Annotated[int, Field(strict=True, ge=1, le=2147483647)]
    product_type: Text | None = None
    target_user: Text | None = None
    problem_or_job: Text | None = None
    context_or_niche: Text | None = None
    market_scope: Text | None = None
    business_model: Text | None = None
    alternatives: Text | None = None
    constraints: Annotated[dict[Name, Text | None], Field(max_length=64)] = Field(default_factory=dict)
    language_scope: Annotated[list[Name], Field(min_length=1, max_length=8)] = Field(default_factory=lambda: ["tr"])
    primary_category: ResearchCategory | None = None
    modifiers: Annotated[list[Name], Field(max_length=32)] = Field(default_factory=list)
    skipped_clarification: Annotated[bool, Field(strict=True)] = False
    continue_with_unknowns: Annotated[bool, Field(strict=True)] = False

    @model_validator(mode="after")
    def explicit_edits(self):
        if self.model_fields_set == {"expected_brief_version"}:
            raise ValueError("at least one human edit is required")
        for name in ("constraints", "language_scope", "modifiers", "skipped_clarification", "continue_with_unknowns"):
            if name in self.model_fields_set and getattr(self, name) is None:
                raise ValueError("this edit cannot be null")
        for name in ("language_scope", "modifiers"):
            values = getattr(self, name)
            if values is not None and len(values) != len(set(values)):
                raise ValueError("list edits must be unique")
        return self


class BriefReference(Contract):
    brief_id: UUID
    brief_version: Positive
    status: Literal["draft", "awaiting_user", "confirmed"]
    created_at: AwareDatetime


class ResearchPreparation(Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    user_id: UUID
    project_id: UUID
    research_id: UUID
    original_idea: Text
    created_at: AwareDatetime
    latest_brief: BriefReference | None


class ResearchPreparationPage(Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    items: list[ResearchPreparation]
    page: PageInfo


class BriefPage(Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    items: list[IdeaBrief]
    page: PageInfo


class PreparationMutationReceipt(Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    operation: Literal["create_research", "revise_brief", "confirm_brief"]
    request_key: UUID
    input_fingerprint: Hash
    user_id: UUID
    project_id: UUID
    research_id: UUID
    brief_id: UUID
    brief_version: Positive
    created_at: AwareDatetime
    brief: IdeaBrief

    @model_validator(mode="after")
    def exact_selection(self):
        if any(getattr(self, name) != getattr(self.brief, name) for name in (
            "user_id", "project_id", "research_id", "brief_id", "brief_version")):
            raise ValueError("receipt must retain its selected immutable brief")
        return self


# Additive Phase 1 HTTP contracts. These are DTOs, not approval or send authority.
Phase1Version = Annotated[int, Field(strict=True, ge=1, le=2147483647)]
ProposalId = Annotated[str, Field(pattern=r"^[A-Za-z][A-Za-z0-9_.:-]{0,63}$")]
Phase1FieldPath = Annotated[str, Field(pattern=r"^(original_idea|product_type|target_user|problem_or_job|context_or_niche|market_scope|business_model|alternatives|constraints\.[A-Za-z_][A-Za-z0-9_-]{0,63})$")]
Phase1SourceId = Annotated[str, Field(pattern=r"^source-[0-9]{4}$")]
Phase1QueryText = Annotated[str, Field(min_length=1, max_length=1000, pattern=r"\S")]


def _phase1_unique(values, label):
    if len(values) != len(set(values)):
        raise ValueError(f"duplicate {label}")


def _phase1_plan_tuple(identity, version, fingerprint):
    if any(v is None for v in (identity, version, fingerprint)) and not all(v is None for v in (identity, version, fingerprint)):
        raise ValueError("plan identity, version and fingerprint must appear together")


class Phase1Contract(Contract):
    @model_validator(mode="after")
    def scalar_unicode(self):
        pending = [self.model_dump(mode="python")]
        while pending:
            value = pending.pop()
            if isinstance(value, str):
                value.encode("utf-8", errors="strict")
            elif isinstance(value, dict):
                pending.extend(value.keys())
                pending.extend(value.values())
            elif isinstance(value, (list, tuple)):
                pending.extend(value)
        return self


class HumanBriefConfirm(Phase1Contract):
    model_config = ConfigDict(json_schema_serialization_defaults_required=False)
    expected_brief_id: UUID
    expected_brief_version: Phase1Version
    analysis_id: UUID | None = None
    accepted_proposal_ids: Annotated[list[ProposalId], Field(max_length=64)] = Field(default_factory=list)
    category_choice: Literal["current", "proposal", "unmatched"]
    category_proposal_id: ProposalId | None = None
    skipped_clarification: Annotated[bool, Field(strict=True)] = False
    continue_with_unknowns: Annotated[bool, Field(strict=True)] = False

    @model_validator(mode="after")
    def explicit_choices(self):
        _phase1_unique(self.accepted_proposal_ids, "accepted proposal")
        if self.accepted_proposal_ids and self.analysis_id is None:
            raise ValueError("proposal acceptance needs an exact analysis")
        if self.category_choice == "proposal":
            if self.analysis_id is None or self.category_proposal_id is None:
                raise ValueError("category proposal needs an exact analysis and proposal")
        elif self.category_proposal_id is not None:
            raise ValueError("only proposal category selection has a proposal ID")
        if self.category_proposal_id in self.accepted_proposal_ids:
            raise ValueError("category and field proposal selections are separate")
        if self.skipped_clarification and not self.continue_with_unknowns:
            raise ValueError("skipped clarification needs explicit continue with unknowns")
        return self


class PreparationAnalysisCreate(Phase1Contract):
    model_config = ConfigDict(json_schema_serialization_defaults_required=False)
    kind: Literal["brief", "plan"]
    expected_brief_id: UUID
    expected_brief_version: Phase1Version
    budget: BudgetLimits
    expected_plan_id: UUID | None = None
    expected_plan_version: Phase1Version | None = None
    expected_plan_fingerprint: Hash | None = None

    @model_validator(mode="after")
    def selected_plan(self):
        _phase1_plan_tuple(self.expected_plan_id, self.expected_plan_version, self.expected_plan_fingerprint)
        if self.kind == "brief" and self.expected_plan_id is not None:
            raise ValueError("brief analysis cannot select a plan")
        return self


class BriefFieldProposal(Phase1Contract):
    proposal_id: ProposalId
    field_path: Phase1FieldPath
    value: Text | None
    origin: Literal["ai_inferred", "ai_hypothesis"]
    assumption_id: ProposalId
    basis_refs: Annotated[list[Phase1FieldPath], Field(min_length=1, max_length=64)]

    @model_validator(mode="after")
    def immutable_original(self):
        if self.field_path == "original_idea":
            raise ValueError("a model cannot propose changing the original idea")
        _phase1_unique(self.basis_refs, "basis reference")
        return self


class CategoryProposal(Phase1Contract):
    proposal_id: ProposalId
    primary_category: ResearchCategory | None
    rationale: Text
    secondary_categories: Annotated[list[ResearchCategory], Field(max_length=6)] = Field(default_factory=list)
    add_on_packages: Annotated[list[AddOnPackage], Field(max_length=8)] = Field(default_factory=list)
    modifiers: Annotated[list[Name], Field(max_length=32)] = Field(default_factory=list)

    @model_validator(mode="after")
    def distinct_categories(self):
        for name in ("secondary_categories", "add_on_packages", "modifiers"):
            _phase1_unique(getattr(self, name), name)
        if self.primary_category in self.secondary_categories:
            raise ValueError("primary category cannot also be secondary")
        return self


class IntentProposal(Phase1Contract):
    proposal_id: ProposalId
    intent: SearchIntent
    question: Text
    priority: Annotated[int, Field(strict=True, ge=1, le=5)]
    brief_basis: Annotated[list[Phase1FieldPath], Field(min_length=1, max_length=64)]
    expected_fields: Annotated[list[Name], Field(max_length=64)]
    required_evidence_types: Annotated[list[EvidenceType], Field(max_length=8)]
    validation_kind: GapKind
    included: Annotated[bool, Field(strict=True)]
    exclusion_reason: Text | None = None

    @model_validator(mode="after")
    def applicability(self):
        if self.included != (self.exclusion_reason is None):
            raise ValueError("only excluded intents require an exclusion reason")
        for name in ("brief_basis", "expected_fields", "required_evidence_types"):
            _phase1_unique(getattr(self, name), name)
        return self


class QueryHypothesis(Phase1Contract):
    proposal_id: ProposalId
    intent_proposal_id: ProposalId
    query_text: Phase1QueryText
    language: Name
    market_scope: Text | None
    origin: Literal["ai_inferred", "ai_hypothesis"]
    basis_refs: Annotated[list[Phase1FieldPath], Field(min_length=1, max_length=64)]

    @model_validator(mode="after")
    def distinct_basis(self):
        _phase1_unique(self.basis_refs, "basis reference")
        return self


class PreparationAnalysis(Envelope, Phase1Contract):
    analysis_id: UUID
    analysis_kind: Literal["brief", "plan"]
    input_brief_id: UUID
    input_brief_version: Phase1Version
    input_plan_id: UUID | None = None
    input_plan_version: Phase1Version | None = None
    input_plan_fingerprint: Hash | None = None
    field_proposals: Annotated[list[BriefFieldProposal], Field(max_length=64)] = Field(default_factory=list)
    normalized_idea: Text | None = None
    category_proposal: CategoryProposal | None = None
    clarifying_questions: Annotated[list[Text], Field(max_length=3)] = Field(default_factory=list)
    missing_fields: Annotated[list[Phase1FieldPath], Field(max_length=64)] = Field(default_factory=list)
    known_unknowns: Annotated[list[Text], Field(max_length=128)] = Field(default_factory=list)
    intent_proposals: Annotated[list[IntentProposal], Field(max_length=64)] = Field(default_factory=list)
    query_hypotheses: Annotated[list[QueryHypothesis], Field(max_length=512)] = Field(default_factory=list)

    @model_validator(mode="after")
    def proposal_lineage(self):
        _phase1_plan_tuple(self.input_plan_id, self.input_plan_version, self.input_plan_fingerprint)
        if self.analysis_kind == "brief" and self.input_plan_id is not None:
            raise ValueError("brief analysis cannot select a plan")
        if self.versions.brief != self.input_brief_version or self.versions.plan != self.input_plan_version:
            raise ValueError("analysis versions must pin their input selection")
        proposals = [p.proposal_id for p in self.field_proposals + self.intent_proposals + self.query_hypotheses]
        if self.category_proposal is not None:
            proposals.append(self.category_proposal.proposal_id)
        _phase1_unique(proposals, "proposal identity")
        _phase1_unique([p.field_path for p in self.field_proposals], "field proposal")
        _phase1_unique([p.assumption_id for p in self.field_proposals], "assumption identity")
        _phase1_unique(self.missing_fields, "missing field")
        included = {i.proposal_id for i in self.intent_proposals if i.included}
        if any(q.intent_proposal_id not in included for q in self.query_hypotheses):
            raise ValueError("query hypothesis needs an included proposed intent")
        return self


class PreparationAnalysisOperation(Phase1Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    user_id: UUID
    project_id: UUID
    research_id: UUID
    operation: Literal["analyze_brief", "propose_plan"]
    request_key: UUID
    input_fingerprint: Hash
    analysis_id: UUID | None
    attempt_id: UUID | None
    input_brief_id: UUID
    input_brief_version: Phase1Version
    input_plan_id: UUID | None = None
    input_plan_version: Phase1Version | None = None
    input_plan_fingerprint: Hash | None = None
    status: Literal["pending", "completed", "invalid_output", "provider_unknown", "overrun", "not_dispatched", "disabled"]
    analysis: PreparationAnalysis | None
    usage: Usage
    created_at: AwareDatetime
    current_scope_matches: Annotated[bool, Field(strict=True)]

    @model_validator(mode="after")
    def exact_analysis(self):
        _phase1_plan_tuple(self.input_plan_id, self.input_plan_version, self.input_plan_fingerprint)
        if self.operation == "analyze_brief" and self.input_plan_id is not None:
            raise ValueError("brief analysis cannot select a plan")
        if (self.status == "completed") != (self.analysis is not None):
            raise ValueError("only completed operations release an analysis")
        if self.status in ("completed", "invalid_output", "provider_unknown", "overrun") and self.attempt_id is None:
            raise ValueError("a dispatched result needs its server attempt identity")
        if (self.status == "provider_unknown") != self.usage.provider_result_unknown:
            raise ValueError("unknown provider accounting must stay explicit")
        if self.analysis is not None:
            for key in ("user_id", "project_id", "research_id", "analysis_id", "input_brief_id", "input_brief_version", "input_plan_id", "input_plan_version", "input_plan_fingerprint"):
                if getattr(self, key) != getattr(self.analysis, key):
                    raise ValueError("operation must retain its exact analysis selection")
            if self.analysis.analysis_kind != ("brief" if self.operation == "analyze_brief" else "plan"):
                raise ValueError("operation and analysis kind must agree")
        return self


class PreparationAnalysisPage(Phase1Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    items: Annotated[list[PreparationAnalysis], Field(max_length=100)]
    page: PageInfo

    @model_validator(mode="after")
    def bounded_history(self):
        _phase1_unique([i.analysis_id for i in self.items], "analysis identity")
        if len(self.items) > self.page.limit or len({(i.user_id, i.project_id, i.research_id) for i in self.items}) > 1:
            raise ValueError("analysis page must retain bounded single-research history")
        return self


class PlanDraftCreate(Phase1Contract):
    model_config = ConfigDict(json_schema_serialization_defaults_required=False)
    expected_brief_id: UUID
    expected_brief_version: Phase1Version
    analysis_id: UUID | None = None
    research_mode: ResearchMode
    budget: BudgetLimits


class PlanQueryEdit(Phase1Contract):
    query_id: UUID
    query_text: Phase1QueryText


class PlanIntentDecision(Phase1Contract):
    intent_id: UUID
    included: Annotated[bool, Field(strict=True)]
    reason: Text | None = None

    @model_validator(mode="after")
    def applicability(self):
        if self.included != (self.reason is None):
            raise ValueError("only excluded intents require a reason")
        return self


class HumanPlanPatch(Phase1Contract):
    model_config = ConfigDict(json_schema_serialization_defaults_required=False)
    expected_plan_id: UUID
    expected_plan_version: Phase1Version
    expected_plan_fingerprint: Hash
    expected_brief_id: UUID
    expected_brief_version: Phase1Version
    research_mode: ResearchMode | None = None
    budget: BudgetLimits | None = None
    excluded_source_ids: Annotated[list[Phase1SourceId], Field(max_length=128)] = Field(default_factory=list)
    excluded_query_ids: Annotated[list[UUID], Field(max_length=512)] = Field(default_factory=list)
    query_edits: Annotated[list[PlanQueryEdit], Field(max_length=512)] = Field(default_factory=list)
    intent_decisions: Annotated[list[PlanIntentDecision], Field(max_length=64)] = Field(default_factory=list)

    @model_validator(mode="after")
    def explicit_edits(self):
        selections = {"expected_plan_id", "expected_plan_version", "expected_plan_fingerprint", "expected_brief_id", "expected_brief_version"}
        if not self.model_fields_set - selections:
            raise ValueError("at least one explicit plan edit is required")
        for name in ("research_mode", "budget"):
            if name in self.model_fields_set and getattr(self, name) is None:
                raise ValueError("this edit cannot be null")
        for name in ("excluded_source_ids", "excluded_query_ids"):
            _phase1_unique(getattr(self, name), name)
        _phase1_unique([q.query_id for q in self.query_edits], "edited query")
        _phase1_unique([i.intent_id for i in self.intent_decisions], "intent decision")
        if set(self.excluded_query_ids).intersection(q.query_id for q in self.query_edits):
            raise ValueError("a query cannot be edited and excluded together")
        return self


class PlanApprovalCreate(Phase1Contract):
    model_config = ConfigDict(json_schema_serialization_defaults_required=False)
    expected_plan_id: UUID
    expected_plan_version: Phase1Version
    expected_plan_fingerprint: Hash
    expected_brief_id: UUID
    expected_brief_version: Phase1Version
    confirmed_query_ids: Annotated[list[UUID], Field(max_length=512)] = Field(default_factory=list)
    acknowledged_gap_ids: Annotated[list[ProposalId], Field(max_length=128)] = Field(default_factory=list)

    @model_validator(mode="after")
    def distinct_selections(self):
        _phase1_unique(self.confirmed_query_ids, "confirmed query")
        _phase1_unique(self.acknowledged_gap_ids, "acknowledged gap")
        return self


class PlanReference(Phase1Contract):
    research_plan_id: UUID
    plan_version: Phase1Version
    plan_fingerprint: Hash
    status: Literal["draft", "awaiting_user", "confirmed"]
    brief_id: UUID
    brief_version: Phase1Version
    created_at: AwareDatetime


class ResearchPlanPage(Phase1Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    items: Annotated[list[ResearchPlan], Field(max_length=100)]
    page: PageInfo

    @model_validator(mode="after")
    def bounded_history(self):
        _phase1_unique([(i.research_plan_id, i.plan_version) for i in self.items], "plan version")
        if len(self.items) > self.page.limit or len({(i.user_id, i.project_id, i.research_id) for i in self.items}) > 1:
            raise ValueError("plan page must retain bounded single-research history")
        return self


class PlanCoverageGap(Phase1Contract):
    gap_id: ProposalId
    intent_id: UUID | None = None
    reason: Text
    source_ids: Annotated[list[Phase1SourceId], Field(max_length=128)] = Field(default_factory=list)
    missing_fields: Annotated[list[Name], Field(max_length=64)] = Field(default_factory=list)
    required: Annotated[bool, Field(strict=True)]

    @model_validator(mode="after")
    def distinct_coverage(self):
        _phase1_unique(self.source_ids, "gap source")
        _phase1_unique(self.missing_fields, "gap field")
        return self


class PlanExecutionEligibility(Phase1Contract):
    can_approve: Annotated[bool, Field(strict=True)]
    can_start: Annotated[bool, Field(strict=True)]
    blocking_reasons: Annotated[list[Name], Field(max_length=128)]
    coverage_gaps: Annotated[list[PlanCoverageGap], Field(max_length=128)]
    qualification_version: Version | None
    qualification_digest: Hash | None
    checked_at: AwareDatetime
    valid_until: AwareDatetime | None

    @model_validator(mode="after")
    def qualification_is_explicit(self):
        _phase1_plan_tuple(self.qualification_version, self.valid_until, self.qualification_digest)
        _phase1_unique(self.blocking_reasons, "blocking reason")
        _phase1_unique([g.gap_id for g in self.coverage_gaps], "coverage gap")
        if self.can_approve and self.can_start:
            raise ValueError("an awaiting approval is not an executable confirmed plan")
        if self.can_approve or self.can_start:
            if self.blocking_reasons or self.valid_until is None or self.valid_until <= self.checked_at:
                raise ValueError("current qualification and no blocking reasons are required")
        return self


class ResearchPlanPreparation(Phase1Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    user_id: UUID
    project_id: UUID
    research_id: UUID
    plan: ResearchPlan
    is_latest: Annotated[bool, Field(strict=True)]
    current_brief: BriefReference
    eligibility: PlanExecutionEligibility

    @model_validator(mode="after")
    def selected_plan(self):
        if any(getattr(self, key) != getattr(self.plan, key) for key in ("user_id", "project_id", "research_id")):
            raise ValueError("preparation must retain its scoped plan")
        eligibility = self.eligibility
        if eligibility.can_approve or eligibility.can_start:
            if (not self.is_latest or (self.plan.brief_id, self.plan.brief_version) != (self.current_brief.brief_id, self.current_brief.brief_version)
                    or self.current_brief.status != "confirmed" or not self.plan.source_plan or not self.plan.query_plan
                    or not any(i.included for i in self.plan.intents)
                    or self.plan.versions.source_registry != eligibility.qualification_version):
                raise ValueError("only exact current qualified nonempty scope is actionable")
            payload = self.plan.model_dump(mode="python")
            payload.update(status="confirmed", confirmed_at=eligibility.checked_at)
            if eligibility.can_approve:
                # The approval form must explicitly confirm these displayed IDs;
                # preview eligibility itself neither changes nor approves the plan.
                for query in payload["query_plan"]:
                    if query["origin"] == FieldOrigin.AI_HYPOTHESIS:
                        query["user_confirmed"] = True
            ResearchPlan.model_validate(payload)  # Retain every existing scope/provenance/permission hard gate.
        if eligibility.can_approve and self.plan.status != "awaiting_user":
            raise ValueError("only an awaiting plan can be approved")
        if eligibility.can_start and self.plan.status != "confirmed":
            raise ValueError("only a confirmed plan can start")
        return self


class PlanMutationReceipt(Phase1Contract):
    schema_version: Literal["1.0.0"] = SCHEMA_VERSION
    user_id: UUID
    project_id: UUID
    research_id: UUID
    operation: Literal["draft_plan", "revise_plan", "approve_plan"]
    request_key: UUID
    input_fingerprint: Hash
    input_brief_id: UUID
    input_brief_version: Phase1Version
    input_plan_id: UUID | None
    input_plan_version: Phase1Version | None
    input_plan_fingerprint: Hash | None
    result_plan_id: UUID
    result_plan_version: Phase1Version
    result_plan_fingerprint: Hash
    created_at: AwareDatetime
    plan: ResearchPlan

    @model_validator(mode="after")
    def exact_selection(self):
        _phase1_plan_tuple(self.input_plan_id, self.input_plan_version, self.input_plan_fingerprint)
        if any(getattr(self, key) != getattr(self.plan, key) for key in ("user_id", "project_id", "research_id")):
            raise ValueError("receipt must retain its scoped plan")
        for actual, selected in ((self.result_plan_id, self.plan.research_plan_id), (self.result_plan_version, self.plan.plan_version),
                                 (self.result_plan_fingerprint, self.plan.plan_fingerprint), (self.input_brief_id, self.plan.brief_id),
                                 (self.input_brief_version, self.plan.brief_version)):
            if actual != selected:
                raise ValueError("receipt must retain its exact result plan")
        if self.operation == "draft_plan":
            if self.input_plan_id is not None or self.plan.status != "awaiting_user":
                raise ValueError("draft receipts select only their new awaiting plan")
        else:
            if self.input_plan_id != self.result_plan_id or self.input_plan_version is None or self.input_plan_version >= self.result_plan_version:
                raise ValueError("revision and approval append a newer version of the selected plan")
            expected = "confirmed" if self.operation == "approve_plan" else "awaiting_user"
            if self.plan.status != expected:
                raise ValueError("operation and result plan status must agree")
        return self


# Explicit export list prevents helpers/legacy preview schemas leaking into the wire catalog.
WIRE_MODELS = (ApiError, BudgetLimits, Usage, Versions, ProvenanceField, BriefContent, IdeaBrief,
               SourcePlanItem, QueryPlanItem, ResearchPlan, SourceCounts, QueryExecution,
               RawArtifact, TextSegment, NormalizedDocument, Claim, Citation, SourceReport,
               EvidenceBundle, SufficiencyAssessment, ResearchGapRequest, ReportStatement,
               DecisionReport, ResearchRun, User, Session, AuthCredentials, ProjectCreate, Project, PageInfo, ProjectPage, RunPage,
               ResearchCreate, HumanBriefPatch, BriefReference, ResearchPreparation, ResearchPreparationPage,
               BriefPage, PreparationMutationReceipt, HumanBriefConfirm, PreparationAnalysisCreate, PreparationAnalysis,
               PreparationAnalysisOperation, PreparationAnalysisPage, PlanDraftCreate, HumanPlanPatch, PlanApprovalCreate,
               PlanReference, ResearchPlanPage, ResearchPlanPreparation, PlanMutationReceipt)
