"""Generate checked-in consumer contracts; --check fails on any drift."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

API_ROOT = Path(__file__).resolve().parents[1]
ROOT = API_ROOT.parent.parent
sys.path.insert(0, str(API_ROOT))
from app.contract_catalog import wire_catalog  # noqa: E402
from contract_examples import producer_examples  # noqa: E402


def ts_type(schema: dict | bool) -> str:
    if isinstance(schema, bool):
        return "unknown" if schema else "never"
    if "$ref" in schema:
        name = schema["$ref"].removeprefix("#/$defs/")
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
            raise ValueError("unsupported schema reference")
        return name
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(v, ensure_ascii=False) for v in schema["enum"])
    for key, operator in [("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")]:
        if key in schema:
            return "(" + operator.join(ts_type(s) for s in schema[key]) + ")"
    kind = schema.get("type")
    if kind == "null":
        return "null"
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "array":
        return "Array<" + ts_type(schema["items"]) + ">"
    if kind == "object":
        props = schema.get("properties", {})
        required = set(schema.get("required", []))
        additional = schema.get("additionalProperties", False)
        fields = [json.dumps(name) + ("" if name in required else "?") + ": " + ts_type(value) + ";" for name, value in props.items()]
        patterns = schema.get("patternProperties", {})
        if not props and "$ref" in schema.get("propertyNames", {}) and additional is not False:
            return "Partial<Record<" + ts_type(schema["propertyNames"]) + ", " + ts_type(additional) + ">>"
        if patterns and additional is False:
            fields.append("[key: string]: " + " | ".join(ts_type(value) for value in patterns.values()) + ";")
        if additional is not False:
            fields.append("[key: string]: " + ts_type(additional) + ";")
        return "{ " + " ".join(fields) + " }" if fields else "Record<string, never>"
    raise ValueError(f"unsupported schema node: {schema}")


def generated_files() -> dict[Path, str]:
    catalog = wire_catalog()
    header = "// Generated by apps/api/scripts/generate_contracts.py. Do not edit.\n"
    ts = header + 'export const schemaVersion = "' + catalog["schema_version"] + '" as const;\n\n'
    ts += "\n\n".join(f"export type {name} = {ts_type(schema)};" for name, schema in catalog["$defs"].items()) + "\n"
    examples = producer_examples()
    fixture = header + 'import type { Versions, BriefContent, RawArtifact, SufficiencyAssessment } from "../src/generated";\n'
    for name, example in examples.items():
        fixture += f"\nexport const {name}: {example.__class__.__name__} = " + json.dumps(example.model_dump(mode="json"), ensure_ascii=False, indent=2) + ";\n"
    fixture += '\n// These invalid consumer values must remain rejected by the generated types.\n'
    fixture += '// @ts-expect-error connector versions are strings\nconst invalidConnector: Versions["connectors"] = { "source-0017": 42 };\n'
    fixture += '// @ts-expect-error qualitative check values are an exact status union\nconst invalidCheck: SufficiencyAssessment["qualitative_checks"] = { "market": "verified" };\n'
    fixture += 'void invalidConnector; void invalidCheck;\n'
    return {
        ROOT / "packages/contracts/tests/producer-consumer.ts": fixture,
        ROOT / "packages/contracts/schema/wire.schema.json": json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        ROOT / "packages/contracts/src/generated.ts": ts,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    drift = []
    for path, text in generated_files().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                drift.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    if drift:
        parser.exit(1, "Contract drift: " + ", ".join(drift) + "\n")
    print("Canonical contracts " + ("match" if args.check else "generated"))


if __name__ == "__main__":
    main()
