import { ArrowRight, Check, Circle, LoaderCircle } from "lucide-react";
import { ProgressIndicator } from "@/components/ui/progress-indicator";
import { currentResearch } from "@/lib/mock-data/dashboard";

const stateIcon = { complete: Check, active: LoaderCircle, pending: Circle };

export function ResearchCard() {
  return <section className="rounded-xl border border-[var(--line)] bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><div className="mb-3 flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[var(--brand)]" /><span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[var(--brand-deep)]">Continue research</span></div><h2 className="text-lg font-semibold tracking-[-0.04em] text-[var(--ink)]">{currentResearch.project}</h2><p className="mt-1 text-sm text-[#73747e]">{currentResearch.segment}</p></div><button className="inline-flex items-center justify-center gap-2 rounded-lg border border-[var(--line)] bg-white px-3.5 py-2 text-xs font-semibold text-[var(--ink)] transition hover:border-[#d8d8e2] hover:bg-[#fafafa]" type="button">Open research <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" /></button></div><div className="mt-7 flex items-end gap-4"><div className="min-w-0 flex-1"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-medium text-[#676873]">Research progress</span><span className="font-mono text-xs font-semibold tabular-nums text-[var(--ink)]">{currentResearch.progress}%</span></div><ProgressIndicator value={currentResearch.progress} /></div><span className="hidden text-[11px] text-[#858690] sm:block">{currentResearch.updatedAt}</span></div><ol className="mt-6 grid gap-3 border-t border-[var(--line)] pt-5 sm:grid-cols-2"><li className="col-span-full text-[10px] font-semibold uppercase tracking-[0.12em] text-[#92939c]">Research activity</li>{currentResearch.steps.map((step) => { const Icon = stateIcon[step.state]; return <li className="flex items-center gap-2.5 text-xs text-[#60616b]" key={step.label}><span className={`grid h-5 w-5 place-items-center rounded-full ${step.state === "complete" ? "bg-[var(--positive-soft)] text-[var(--positive)]" : step.state === "active" ? "bg-[var(--brand-soft)] text-[var(--brand)]" : "bg-[#f1f1f3] text-[#9697a0]"}`}><Icon aria-hidden="true" className={`h-3 w-3 ${step.state === "active" ? "animate-spin" : ""}`} /></span>{step.label}</li>; })}</ol></section>;
}
